// source: android_metadata_update.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.android_metadata_update.commentsUpdateMsg', null, global);
goog.exportSymbol('proto.android_metadata_update.root', null, global);
goog.exportSymbol('proto.android_metadata_update.root.contextType', null, global);
goog.exportSymbol('proto.android_metadata_update.root.contextType.clientType', null, global);
goog.exportSymbol('proto.android_metadata_update.stringUpdateMsg', null, global);
goog.exportSymbol('proto.android_metadata_update.updateToggle', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.updateToggle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_metadata_update.updateToggle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.updateToggle.displayName = 'proto.android_metadata_update.updateToggle';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.stringUpdateMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_metadata_update.stringUpdateMsg.repeatedFields_, null);
};
goog.inherits(proto.android_metadata_update.stringUpdateMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.stringUpdateMsg.displayName = 'proto.android_metadata_update.stringUpdateMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.commentsUpdateMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_metadata_update.commentsUpdateMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.commentsUpdateMsg.displayName = 'proto.android_metadata_update.commentsUpdateMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_metadata_update.root.repeatedFields_, null);
};
goog.inherits(proto.android_metadata_update.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.root.displayName = 'proto.android_metadata_update.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.root.contextType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_metadata_update.root.contextType.repeatedFields_, null);
};
goog.inherits(proto.android_metadata_update.root.contextType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.root.contextType.displayName = 'proto.android_metadata_update.root.contextType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_metadata_update.root.contextType.clientType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_metadata_update.root.contextType.clientType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_metadata_update.root.contextType.clientType.displayName = 'proto.android_metadata_update.root.contextType.clientType';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.updateToggle.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.updateToggle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.updateToggle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.updateToggle.toObject = function(includeInstance, msg) {
  var f, obj = {
    updatefield: jspb.Message.getFieldWithDefault(msg, 1, 0),
    updatevalue: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.updateToggle}
 */
proto.android_metadata_update.updateToggle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.updateToggle;
  return proto.android_metadata_update.updateToggle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.updateToggle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.updateToggle}
 */
proto.android_metadata_update.updateToggle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUpdatefield(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUpdatevalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.updateToggle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.updateToggle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.updateToggle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.updateToggle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 updateField = 1;
 * @return {number}
 */
proto.android_metadata_update.updateToggle.prototype.getUpdatefield = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.updateToggle} returns this
 */
proto.android_metadata_update.updateToggle.prototype.setUpdatefield = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.android_metadata_update.updateToggle} returns this
 */
proto.android_metadata_update.updateToggle.prototype.clearUpdatefield = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.android_metadata_update.updateToggle.prototype.hasUpdatefield = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 updateValue = 2;
 * @return {number}
 */
proto.android_metadata_update.updateToggle.prototype.getUpdatevalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.updateToggle} returns this
 */
proto.android_metadata_update.updateToggle.prototype.setUpdatevalue = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.android_metadata_update.updateToggle} returns this
 */
proto.android_metadata_update.updateToggle.prototype.clearUpdatevalue = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.android_metadata_update.updateToggle.prototype.hasUpdatevalue = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_metadata_update.stringUpdateMsg.repeatedFields_ = [1,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.stringUpdateMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.stringUpdateMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.stringUpdateMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    newstringList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    placenameList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    paramstringList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    updatetype: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.stringUpdateMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.stringUpdateMsg;
  return proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.stringUpdateMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addNewstring(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addPlacename(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addParamstring(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUpdatetype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.stringUpdateMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNewstringList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getPlacenameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getParamstringList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getUpdatetype();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * repeated string newString = 1;
 * @return {!Array<string>}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.getNewstringList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.setNewstringList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.addNewstring = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.clearNewstringList = function() {
  return this.setNewstringList([]);
};


/**
 * repeated string placeName = 3;
 * @return {!Array<string>}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.getPlacenameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.setPlacenameList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.addPlacename = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.clearPlacenameList = function() {
  return this.setPlacenameList([]);
};


/**
 * repeated string paramString = 4;
 * @return {!Array<string>}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.getParamstringList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.setParamstringList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.addParamstring = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.clearParamstringList = function() {
  return this.setParamstringList([]);
};


/**
 * optional int32 updateType = 5;
 * @return {number}
 */
proto.android_metadata_update.stringUpdateMsg.prototype.getUpdatetype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.stringUpdateMsg} returns this
 */
proto.android_metadata_update.stringUpdateMsg.prototype.setUpdatetype = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.commentsUpdateMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.commentsUpdateMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.commentsUpdateMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    moderationtype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    int4: jspb.Message.getFieldWithDefault(msg, 4, 0),
    int5: jspb.Message.getFieldWithDefault(msg, 5, 0),
    allowcomments: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.commentsUpdateMsg}
 */
proto.android_metadata_update.commentsUpdateMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.commentsUpdateMsg;
  return proto.android_metadata_update.commentsUpdateMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.commentsUpdateMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.commentsUpdateMsg}
 */
proto.android_metadata_update.commentsUpdateMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setModerationtype(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInt4(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInt5(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAllowcomments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.commentsUpdateMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.commentsUpdateMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.commentsUpdateMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModerationtype();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getInt4();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getInt5();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getAllowcomments();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional int32 moderationType = 2;
 * @return {number}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.getModerationtype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.commentsUpdateMsg} returns this
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.setModerationtype = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 int4 = 4;
 * @return {number}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.getInt4 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.commentsUpdateMsg} returns this
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.setInt4 = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 int5 = 5;
 * @return {number}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.getInt5 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.commentsUpdateMsg} returns this
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.setInt5 = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 allowComments = 6;
 * @return {number}
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.getAllowcomments = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.commentsUpdateMsg} returns this
 */
proto.android_metadata_update.commentsUpdateMsg.prototype.setAllowcomments = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_metadata_update.root.repeatedFields_ = [1,3,4,6,9,13,20,38,39];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.root.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    contextList: jspb.Message.toObjectList(msg.getContextList(),
    proto.android_metadata_update.root.contextType.toObject, includeInstance),
    browseid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    titleupdateList: jspb.Message.toObjectList(msg.getTitleupdateList(),
    proto.android_metadata_update.stringUpdateMsg.toObject, includeInstance),
    descriptionupdateList: jspb.Message.toObjectList(msg.getDescriptionupdateList(),
    proto.android_metadata_update.stringUpdateMsg.toObject, includeInstance),
    tagsupdateList: jspb.Message.toObjectList(msg.getTagsupdateList(),
    proto.android_metadata_update.stringUpdateMsg.toObject, includeInstance),
    commentsupdateList: jspb.Message.toObjectList(msg.getCommentsupdateList(),
    proto.android_metadata_update.commentsUpdateMsg.toObject, includeInstance),
    locationupdateList: jspb.Message.toObjectList(msg.getLocationupdateList(),
    proto.android_metadata_update.stringUpdateMsg.toObject, includeInstance),
    thumbnailupdateList: jspb.Message.toObjectList(msg.getThumbnailupdateList(),
    proto.android_metadata_update.updateToggle.toObject, includeInstance),
    videoprivacyList: jspb.Message.toObjectList(msg.getVideoprivacyList(),
    proto.android_metadata_update.updateToggle.toObject, includeInstance),
    updateprivacysettingsList: jspb.Message.toObjectList(msg.getUpdateprivacysettingsList(),
    proto.android_metadata_update.updateToggle.toObject, includeInstance),
    eightythree: jspb.Message.getFieldWithDefault(msg, 83, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.root}
 */
proto.android_metadata_update.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.root;
  return proto.android_metadata_update.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.root}
 */
proto.android_metadata_update.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.android_metadata_update.root.contextType;
      reader.readMessage(value,proto.android_metadata_update.root.contextType.deserializeBinaryFromReader);
      msg.addContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrowseid(value);
      break;
    case 3:
      var value = new proto.android_metadata_update.stringUpdateMsg;
      reader.readMessage(value,proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader);
      msg.addTitleupdate(value);
      break;
    case 4:
      var value = new proto.android_metadata_update.stringUpdateMsg;
      reader.readMessage(value,proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader);
      msg.addDescriptionupdate(value);
      break;
    case 6:
      var value = new proto.android_metadata_update.stringUpdateMsg;
      reader.readMessage(value,proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader);
      msg.addTagsupdate(value);
      break;
    case 9:
      var value = new proto.android_metadata_update.commentsUpdateMsg;
      reader.readMessage(value,proto.android_metadata_update.commentsUpdateMsg.deserializeBinaryFromReader);
      msg.addCommentsupdate(value);
      break;
    case 13:
      var value = new proto.android_metadata_update.stringUpdateMsg;
      reader.readMessage(value,proto.android_metadata_update.stringUpdateMsg.deserializeBinaryFromReader);
      msg.addLocationupdate(value);
      break;
    case 20:
      var value = new proto.android_metadata_update.updateToggle;
      reader.readMessage(value,proto.android_metadata_update.updateToggle.deserializeBinaryFromReader);
      msg.addThumbnailupdate(value);
      break;
    case 38:
      var value = new proto.android_metadata_update.updateToggle;
      reader.readMessage(value,proto.android_metadata_update.updateToggle.deserializeBinaryFromReader);
      msg.addVideoprivacy(value);
      break;
    case 39:
      var value = new proto.android_metadata_update.updateToggle;
      reader.readMessage(value,proto.android_metadata_update.updateToggle.deserializeBinaryFromReader);
      msg.addUpdateprivacysettings(value);
      break;
    case 83:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEightythree(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContextList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.android_metadata_update.root.contextType.serializeBinaryToWriter
    );
  }
  f = message.getBrowseid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTitleupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getDescriptionupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getTagsupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getCommentsupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.android_metadata_update.commentsUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getLocationupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.android_metadata_update.stringUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getThumbnailupdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.android_metadata_update.updateToggle.serializeBinaryToWriter
    );
  }
  f = message.getVideoprivacyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      38,
      f,
      proto.android_metadata_update.updateToggle.serializeBinaryToWriter
    );
  }
  f = message.getUpdateprivacysettingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      39,
      f,
      proto.android_metadata_update.updateToggle.serializeBinaryToWriter
    );
  }
  f = message.getEightythree();
  if (f !== 0) {
    writer.writeInt32(
      83,
      f
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_metadata_update.root.contextType.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.root.contextType.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.root.contextType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.root.contextType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.contextType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientList: jspb.Message.toObjectList(msg.getClientList(),
    proto.android_metadata_update.root.contextType.clientType.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.root.contextType}
 */
proto.android_metadata_update.root.contextType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.root.contextType;
  return proto.android_metadata_update.root.contextType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.root.contextType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.root.contextType}
 */
proto.android_metadata_update.root.contextType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.android_metadata_update.root.contextType.clientType;
      reader.readMessage(value,proto.android_metadata_update.root.contextType.clientType.deserializeBinaryFromReader);
      msg.addClient(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.root.contextType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.root.contextType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.root.contextType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.contextType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.android_metadata_update.root.contextType.clientType.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.toObject = function(opt_includeInstance) {
  return proto.android_metadata_update.root.contextType.clientType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_metadata_update.root.contextType.clientType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.contextType.clientType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientnumber: jspb.Message.getFieldWithDefault(msg, 16, 0),
    clientversion: jspb.Message.getFieldWithDefault(msg, 17, ""),
    osname: jspb.Message.getFieldWithDefault(msg, 18, ""),
    osversion: jspb.Message.getFieldWithDefault(msg, 19, ""),
    androidsdkversion: jspb.Message.getFieldWithDefault(msg, 64, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_metadata_update.root.contextType.clientType}
 */
proto.android_metadata_update.root.contextType.clientType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_metadata_update.root.contextType.clientType;
  return proto.android_metadata_update.root.contextType.clientType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_metadata_update.root.contextType.clientType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_metadata_update.root.contextType.clientType}
 */
proto.android_metadata_update.root.contextType.clientType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientnumber(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientversion(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsname(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsversion(value);
      break;
    case 64:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAndroidsdkversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_metadata_update.root.contextType.clientType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_metadata_update.root.contextType.clientType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_metadata_update.root.contextType.clientType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientnumber();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getClientversion();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getOsname();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getOsversion();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getAndroidsdkversion();
  if (f !== 0) {
    writer.writeInt32(
      64,
      f
    );
  }
};


/**
 * optional int32 clientNumber = 16;
 * @return {number}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.getClientnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.root.contextType.clientType} returns this
 */
proto.android_metadata_update.root.contextType.clientType.prototype.setClientnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string clientVersion = 17;
 * @return {string}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.getClientversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_metadata_update.root.contextType.clientType} returns this
 */
proto.android_metadata_update.root.contextType.clientType.prototype.setClientversion = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string osName = 18;
 * @return {string}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.getOsname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_metadata_update.root.contextType.clientType} returns this
 */
proto.android_metadata_update.root.contextType.clientType.prototype.setOsname = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string osVersion = 19;
 * @return {string}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.getOsversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_metadata_update.root.contextType.clientType} returns this
 */
proto.android_metadata_update.root.contextType.clientType.prototype.setOsversion = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional int32 androidSdkVersion = 64;
 * @return {number}
 */
proto.android_metadata_update.root.contextType.clientType.prototype.getAndroidsdkversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 64, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.root.contextType.clientType} returns this
 */
proto.android_metadata_update.root.contextType.clientType.prototype.setAndroidsdkversion = function(value) {
  return jspb.Message.setProto3IntField(this, 64, value);
};


/**
 * repeated clientType client = 1;
 * @return {!Array<!proto.android_metadata_update.root.contextType.clientType>}
 */
proto.android_metadata_update.root.contextType.prototype.getClientList = function() {
  return /** @type{!Array<!proto.android_metadata_update.root.contextType.clientType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.root.contextType.clientType, 1));
};


/**
 * @param {!Array<!proto.android_metadata_update.root.contextType.clientType>} value
 * @return {!proto.android_metadata_update.root.contextType} returns this
*/
proto.android_metadata_update.root.contextType.prototype.setClientList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.android_metadata_update.root.contextType.clientType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.root.contextType.clientType}
 */
proto.android_metadata_update.root.contextType.prototype.addClient = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.android_metadata_update.root.contextType.clientType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root.contextType} returns this
 */
proto.android_metadata_update.root.contextType.prototype.clearClientList = function() {
  return this.setClientList([]);
};


/**
 * repeated contextType context = 1;
 * @return {!Array<!proto.android_metadata_update.root.contextType>}
 */
proto.android_metadata_update.root.prototype.getContextList = function() {
  return /** @type{!Array<!proto.android_metadata_update.root.contextType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.root.contextType, 1));
};


/**
 * @param {!Array<!proto.android_metadata_update.root.contextType>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setContextList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.android_metadata_update.root.contextType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.root.contextType}
 */
proto.android_metadata_update.root.prototype.addContext = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.android_metadata_update.root.contextType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearContextList = function() {
  return this.setContextList([]);
};


/**
 * optional string browseId = 2;
 * @return {string}
 */
proto.android_metadata_update.root.prototype.getBrowseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.setBrowseid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated stringUpdateMsg titleUpdate = 3;
 * @return {!Array<!proto.android_metadata_update.stringUpdateMsg>}
 */
proto.android_metadata_update.root.prototype.getTitleupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.stringUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.stringUpdateMsg, 3));
};


/**
 * @param {!Array<!proto.android_metadata_update.stringUpdateMsg>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setTitleupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.android_metadata_update.stringUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.root.prototype.addTitleupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.android_metadata_update.stringUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearTitleupdateList = function() {
  return this.setTitleupdateList([]);
};


/**
 * repeated stringUpdateMsg descriptionUpdate = 4;
 * @return {!Array<!proto.android_metadata_update.stringUpdateMsg>}
 */
proto.android_metadata_update.root.prototype.getDescriptionupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.stringUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.stringUpdateMsg, 4));
};


/**
 * @param {!Array<!proto.android_metadata_update.stringUpdateMsg>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setDescriptionupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.android_metadata_update.stringUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.root.prototype.addDescriptionupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.android_metadata_update.stringUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearDescriptionupdateList = function() {
  return this.setDescriptionupdateList([]);
};


/**
 * repeated stringUpdateMsg tagsUpdate = 6;
 * @return {!Array<!proto.android_metadata_update.stringUpdateMsg>}
 */
proto.android_metadata_update.root.prototype.getTagsupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.stringUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.stringUpdateMsg, 6));
};


/**
 * @param {!Array<!proto.android_metadata_update.stringUpdateMsg>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setTagsupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.android_metadata_update.stringUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.root.prototype.addTagsupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.android_metadata_update.stringUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearTagsupdateList = function() {
  return this.setTagsupdateList([]);
};


/**
 * repeated commentsUpdateMsg commentsUpdate = 9;
 * @return {!Array<!proto.android_metadata_update.commentsUpdateMsg>}
 */
proto.android_metadata_update.root.prototype.getCommentsupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.commentsUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.commentsUpdateMsg, 9));
};


/**
 * @param {!Array<!proto.android_metadata_update.commentsUpdateMsg>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setCommentsupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.android_metadata_update.commentsUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.commentsUpdateMsg}
 */
proto.android_metadata_update.root.prototype.addCommentsupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.android_metadata_update.commentsUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearCommentsupdateList = function() {
  return this.setCommentsupdateList([]);
};


/**
 * repeated stringUpdateMsg locationUpdate = 13;
 * @return {!Array<!proto.android_metadata_update.stringUpdateMsg>}
 */
proto.android_metadata_update.root.prototype.getLocationupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.stringUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.stringUpdateMsg, 13));
};


/**
 * @param {!Array<!proto.android_metadata_update.stringUpdateMsg>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setLocationupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.android_metadata_update.stringUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.stringUpdateMsg}
 */
proto.android_metadata_update.root.prototype.addLocationupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.android_metadata_update.stringUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearLocationupdateList = function() {
  return this.setLocationupdateList([]);
};


/**
 * repeated updateToggle thumbnailUpdate = 20;
 * @return {!Array<!proto.android_metadata_update.updateToggle>}
 */
proto.android_metadata_update.root.prototype.getThumbnailupdateList = function() {
  return /** @type{!Array<!proto.android_metadata_update.updateToggle>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.updateToggle, 20));
};


/**
 * @param {!Array<!proto.android_metadata_update.updateToggle>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setThumbnailupdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.android_metadata_update.updateToggle=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.updateToggle}
 */
proto.android_metadata_update.root.prototype.addThumbnailupdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.android_metadata_update.updateToggle, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearThumbnailupdateList = function() {
  return this.setThumbnailupdateList([]);
};


/**
 * repeated updateToggle videoPrivacy = 38;
 * @return {!Array<!proto.android_metadata_update.updateToggle>}
 */
proto.android_metadata_update.root.prototype.getVideoprivacyList = function() {
  return /** @type{!Array<!proto.android_metadata_update.updateToggle>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.updateToggle, 38));
};


/**
 * @param {!Array<!proto.android_metadata_update.updateToggle>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setVideoprivacyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 38, value);
};


/**
 * @param {!proto.android_metadata_update.updateToggle=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.updateToggle}
 */
proto.android_metadata_update.root.prototype.addVideoprivacy = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 38, opt_value, proto.android_metadata_update.updateToggle, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearVideoprivacyList = function() {
  return this.setVideoprivacyList([]);
};


/**
 * repeated updateToggle updatePrivacySettings = 39;
 * @return {!Array<!proto.android_metadata_update.updateToggle>}
 */
proto.android_metadata_update.root.prototype.getUpdateprivacysettingsList = function() {
  return /** @type{!Array<!proto.android_metadata_update.updateToggle>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_metadata_update.updateToggle, 39));
};


/**
 * @param {!Array<!proto.android_metadata_update.updateToggle>} value
 * @return {!proto.android_metadata_update.root} returns this
*/
proto.android_metadata_update.root.prototype.setUpdateprivacysettingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 39, value);
};


/**
 * @param {!proto.android_metadata_update.updateToggle=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_metadata_update.updateToggle}
 */
proto.android_metadata_update.root.prototype.addUpdateprivacysettings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 39, opt_value, proto.android_metadata_update.updateToggle, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.clearUpdateprivacysettingsList = function() {
  return this.setUpdateprivacysettingsList([]);
};


/**
 * optional int32 eightythree = 83;
 * @return {number}
 */
proto.android_metadata_update.root.prototype.getEightythree = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 83, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_metadata_update.root} returns this
 */
proto.android_metadata_update.root.prototype.setEightythree = function(value) {
  return jspb.Message.setProto3IntField(this, 83, value);
};


goog.object.extend(exports, proto.android_metadata_update);
