// source: android_user_metadata.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.android_user_metadata.root', null, global);
goog.exportSymbol('proto.android_user_metadata.root.channelAboutTab', null, global);
goog.exportSymbol('proto.android_user_metadata.root.contextType', null, global);
goog.exportSymbol('proto.android_user_metadata.root.contextType.clientType', null, global);
goog.exportSymbol('proto.android_user_metadata.stringUpdateMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_user_metadata.stringUpdateMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_user_metadata.stringUpdateMsg.repeatedFields_, null);
};
goog.inherits(proto.android_user_metadata.stringUpdateMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_user_metadata.stringUpdateMsg.displayName = 'proto.android_user_metadata.stringUpdateMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_user_metadata.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_user_metadata.root.repeatedFields_, null);
};
goog.inherits(proto.android_user_metadata.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_user_metadata.root.displayName = 'proto.android_user_metadata.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_user_metadata.root.contextType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_user_metadata.root.contextType.repeatedFields_, null);
};
goog.inherits(proto.android_user_metadata.root.contextType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_user_metadata.root.contextType.displayName = 'proto.android_user_metadata.root.contextType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_user_metadata.root.contextType.clientType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_user_metadata.root.contextType.clientType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_user_metadata.root.contextType.clientType.displayName = 'proto.android_user_metadata.root.contextType.clientType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_user_metadata.root.channelAboutTab = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_user_metadata.root.channelAboutTab, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_user_metadata.root.channelAboutTab.displayName = 'proto.android_user_metadata.root.channelAboutTab';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_user_metadata.stringUpdateMsg.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_user_metadata.stringUpdateMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.android_user_metadata.stringUpdateMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_user_metadata.stringUpdateMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.stringUpdateMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    newstringList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_user_metadata.stringUpdateMsg}
 */
proto.android_user_metadata.stringUpdateMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_user_metadata.stringUpdateMsg;
  return proto.android_user_metadata.stringUpdateMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_user_metadata.stringUpdateMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_user_metadata.stringUpdateMsg}
 */
proto.android_user_metadata.stringUpdateMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addNewstring(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_user_metadata.stringUpdateMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_user_metadata.stringUpdateMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_user_metadata.stringUpdateMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.stringUpdateMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNewstringList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string newString = 1;
 * @return {!Array<string>}
 */
proto.android_user_metadata.stringUpdateMsg.prototype.getNewstringList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.android_user_metadata.stringUpdateMsg} returns this
 */
proto.android_user_metadata.stringUpdateMsg.prototype.setNewstringList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.android_user_metadata.stringUpdateMsg} returns this
 */
proto.android_user_metadata.stringUpdateMsg.prototype.addNewstring = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_user_metadata.stringUpdateMsg} returns this
 */
proto.android_user_metadata.stringUpdateMsg.prototype.clearNewstringList = function() {
  return this.setNewstringList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_user_metadata.root.repeatedFields_ = [1,9,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_user_metadata.root.prototype.toObject = function(opt_includeInstance) {
  return proto.android_user_metadata.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_user_metadata.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    contextList: jspb.Message.toObjectList(msg.getContextList(),
    proto.android_user_metadata.root.contextType.toObject, includeInstance),
    browseid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    avatarblobList: jspb.Message.toObjectList(msg.getAvatarblobList(),
    proto.android_user_metadata.stringUpdateMsg.toObject, includeInstance),
    aboutList: jspb.Message.toObjectList(msg.getAboutList(),
    proto.android_user_metadata.root.channelAboutTab.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_user_metadata.root}
 */
proto.android_user_metadata.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_user_metadata.root;
  return proto.android_user_metadata.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_user_metadata.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_user_metadata.root}
 */
proto.android_user_metadata.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.android_user_metadata.root.contextType;
      reader.readMessage(value,proto.android_user_metadata.root.contextType.deserializeBinaryFromReader);
      msg.addContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrowseid(value);
      break;
    case 9:
      var value = new proto.android_user_metadata.stringUpdateMsg;
      reader.readMessage(value,proto.android_user_metadata.stringUpdateMsg.deserializeBinaryFromReader);
      msg.addAvatarblob(value);
      break;
    case 11:
      var value = new proto.android_user_metadata.root.channelAboutTab;
      reader.readMessage(value,proto.android_user_metadata.root.channelAboutTab.deserializeBinaryFromReader);
      msg.addAbout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_user_metadata.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_user_metadata.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_user_metadata.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContextList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.android_user_metadata.root.contextType.serializeBinaryToWriter
    );
  }
  f = message.getBrowseid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAvatarblobList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.android_user_metadata.stringUpdateMsg.serializeBinaryToWriter
    );
  }
  f = message.getAboutList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.android_user_metadata.root.channelAboutTab.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_user_metadata.root.contextType.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_user_metadata.root.contextType.prototype.toObject = function(opt_includeInstance) {
  return proto.android_user_metadata.root.contextType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_user_metadata.root.contextType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.contextType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientList: jspb.Message.toObjectList(msg.getClientList(),
    proto.android_user_metadata.root.contextType.clientType.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_user_metadata.root.contextType}
 */
proto.android_user_metadata.root.contextType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_user_metadata.root.contextType;
  return proto.android_user_metadata.root.contextType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_user_metadata.root.contextType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_user_metadata.root.contextType}
 */
proto.android_user_metadata.root.contextType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.android_user_metadata.root.contextType.clientType;
      reader.readMessage(value,proto.android_user_metadata.root.contextType.clientType.deserializeBinaryFromReader);
      msg.addClient(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_user_metadata.root.contextType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_user_metadata.root.contextType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_user_metadata.root.contextType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.contextType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.android_user_metadata.root.contextType.clientType.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.toObject = function(opt_includeInstance) {
  return proto.android_user_metadata.root.contextType.clientType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_user_metadata.root.contextType.clientType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.contextType.clientType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientnumber: jspb.Message.getFieldWithDefault(msg, 16, 0),
    clientversion: jspb.Message.getFieldWithDefault(msg, 17, ""),
    osname: jspb.Message.getFieldWithDefault(msg, 18, ""),
    osversion: jspb.Message.getFieldWithDefault(msg, 19, ""),
    androidsdkversion: jspb.Message.getFieldWithDefault(msg, 64, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_user_metadata.root.contextType.clientType}
 */
proto.android_user_metadata.root.contextType.clientType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_user_metadata.root.contextType.clientType;
  return proto.android_user_metadata.root.contextType.clientType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_user_metadata.root.contextType.clientType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_user_metadata.root.contextType.clientType}
 */
proto.android_user_metadata.root.contextType.clientType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientnumber(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientversion(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsname(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsversion(value);
      break;
    case 64:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAndroidsdkversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_user_metadata.root.contextType.clientType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_user_metadata.root.contextType.clientType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.contextType.clientType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientnumber();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getClientversion();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getOsname();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getOsversion();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getAndroidsdkversion();
  if (f !== 0) {
    writer.writeInt32(
      64,
      f
    );
  }
};


/**
 * optional int32 clientNumber = 16;
 * @return {number}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.getClientnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_user_metadata.root.contextType.clientType} returns this
 */
proto.android_user_metadata.root.contextType.clientType.prototype.setClientnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string clientVersion = 17;
 * @return {string}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.getClientversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_user_metadata.root.contextType.clientType} returns this
 */
proto.android_user_metadata.root.contextType.clientType.prototype.setClientversion = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string osName = 18;
 * @return {string}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.getOsname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_user_metadata.root.contextType.clientType} returns this
 */
proto.android_user_metadata.root.contextType.clientType.prototype.setOsname = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string osVersion = 19;
 * @return {string}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.getOsversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_user_metadata.root.contextType.clientType} returns this
 */
proto.android_user_metadata.root.contextType.clientType.prototype.setOsversion = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional int32 androidSdkVersion = 64;
 * @return {number}
 */
proto.android_user_metadata.root.contextType.clientType.prototype.getAndroidsdkversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 64, 0));
};


/**
 * @param {number} value
 * @return {!proto.android_user_metadata.root.contextType.clientType} returns this
 */
proto.android_user_metadata.root.contextType.clientType.prototype.setAndroidsdkversion = function(value) {
  return jspb.Message.setProto3IntField(this, 64, value);
};


/**
 * repeated clientType client = 1;
 * @return {!Array<!proto.android_user_metadata.root.contextType.clientType>}
 */
proto.android_user_metadata.root.contextType.prototype.getClientList = function() {
  return /** @type{!Array<!proto.android_user_metadata.root.contextType.clientType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_user_metadata.root.contextType.clientType, 1));
};


/**
 * @param {!Array<!proto.android_user_metadata.root.contextType.clientType>} value
 * @return {!proto.android_user_metadata.root.contextType} returns this
*/
proto.android_user_metadata.root.contextType.prototype.setClientList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.android_user_metadata.root.contextType.clientType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_user_metadata.root.contextType.clientType}
 */
proto.android_user_metadata.root.contextType.prototype.addClient = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.android_user_metadata.root.contextType.clientType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_user_metadata.root.contextType} returns this
 */
proto.android_user_metadata.root.contextType.prototype.clearClientList = function() {
  return this.setClientList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_user_metadata.root.channelAboutTab.prototype.toObject = function(opt_includeInstance) {
  return proto.android_user_metadata.root.channelAboutTab.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_user_metadata.root.channelAboutTab} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.channelAboutTab.toObject = function(includeInstance, msg) {
  var f, obj = {
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_user_metadata.root.channelAboutTab}
 */
proto.android_user_metadata.root.channelAboutTab.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_user_metadata.root.channelAboutTab;
  return proto.android_user_metadata.root.channelAboutTab.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_user_metadata.root.channelAboutTab} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_user_metadata.root.channelAboutTab}
 */
proto.android_user_metadata.root.channelAboutTab.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_user_metadata.root.channelAboutTab.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_user_metadata.root.channelAboutTab.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_user_metadata.root.channelAboutTab} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_user_metadata.root.channelAboutTab.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.android_user_metadata.root.channelAboutTab.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_user_metadata.root.channelAboutTab} returns this
 */
proto.android_user_metadata.root.channelAboutTab.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated contextType context = 1;
 * @return {!Array<!proto.android_user_metadata.root.contextType>}
 */
proto.android_user_metadata.root.prototype.getContextList = function() {
  return /** @type{!Array<!proto.android_user_metadata.root.contextType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_user_metadata.root.contextType, 1));
};


/**
 * @param {!Array<!proto.android_user_metadata.root.contextType>} value
 * @return {!proto.android_user_metadata.root} returns this
*/
proto.android_user_metadata.root.prototype.setContextList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.android_user_metadata.root.contextType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_user_metadata.root.contextType}
 */
proto.android_user_metadata.root.prototype.addContext = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.android_user_metadata.root.contextType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_user_metadata.root} returns this
 */
proto.android_user_metadata.root.prototype.clearContextList = function() {
  return this.setContextList([]);
};


/**
 * optional string browseId = 2;
 * @return {string}
 */
proto.android_user_metadata.root.prototype.getBrowseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_user_metadata.root} returns this
 */
proto.android_user_metadata.root.prototype.setBrowseid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated stringUpdateMsg avatarBlob = 9;
 * @return {!Array<!proto.android_user_metadata.stringUpdateMsg>}
 */
proto.android_user_metadata.root.prototype.getAvatarblobList = function() {
  return /** @type{!Array<!proto.android_user_metadata.stringUpdateMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_user_metadata.stringUpdateMsg, 9));
};


/**
 * @param {!Array<!proto.android_user_metadata.stringUpdateMsg>} value
 * @return {!proto.android_user_metadata.root} returns this
*/
proto.android_user_metadata.root.prototype.setAvatarblobList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.android_user_metadata.stringUpdateMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_user_metadata.stringUpdateMsg}
 */
proto.android_user_metadata.root.prototype.addAvatarblob = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.android_user_metadata.stringUpdateMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_user_metadata.root} returns this
 */
proto.android_user_metadata.root.prototype.clearAvatarblobList = function() {
  return this.setAvatarblobList([]);
};


/**
 * repeated channelAboutTab about = 11;
 * @return {!Array<!proto.android_user_metadata.root.channelAboutTab>}
 */
proto.android_user_metadata.root.prototype.getAboutList = function() {
  return /** @type{!Array<!proto.android_user_metadata.root.channelAboutTab>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_user_metadata.root.channelAboutTab, 11));
};


/**
 * @param {!Array<!proto.android_user_metadata.root.channelAboutTab>} value
 * @return {!proto.android_user_metadata.root} returns this
*/
proto.android_user_metadata.root.prototype.setAboutList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.android_user_metadata.root.channelAboutTab=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_user_metadata.root.channelAboutTab}
 */
proto.android_user_metadata.root.prototype.addAbout = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.android_user_metadata.root.channelAboutTab, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_user_metadata.root} returns this
 */
proto.android_user_metadata.root.prototype.clearAboutList = function() {
  return this.setAboutList([]);
};


goog.object.extend(exports, proto.android_user_metadata);
