// source: android_resolve.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.android_resolve.browseNavigation', null, global);
goog.exportSymbol('proto.android_resolve.root', null, global);
goog.exportSymbol('proto.android_resolve.root.contents', null, global);
goog.exportSymbol('proto.android_resolve.searchNavigation', null, global);
goog.exportSymbol('proto.android_resolve.videoNavigation', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_resolve.browseNavigation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_resolve.browseNavigation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_resolve.browseNavigation.displayName = 'proto.android_resolve.browseNavigation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_resolve.videoNavigation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_resolve.videoNavigation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_resolve.videoNavigation.displayName = 'proto.android_resolve.videoNavigation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_resolve.searchNavigation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.android_resolve.searchNavigation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_resolve.searchNavigation.displayName = 'proto.android_resolve.searchNavigation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_resolve.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.android_resolve.root.repeatedFields_, null);
};
goog.inherits(proto.android_resolve.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_resolve.root.displayName = 'proto.android_resolve.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.android_resolve.root.contents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.android_resolve.root.contents.repeatedFields_, null);
};
goog.inherits(proto.android_resolve.root.contents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.android_resolve.root.contents.displayName = 'proto.android_resolve.root.contents';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_resolve.browseNavigation.prototype.toObject = function(opt_includeInstance) {
  return proto.android_resolve.browseNavigation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_resolve.browseNavigation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.browseNavigation.toObject = function(includeInstance, msg) {
  var f, obj = {
    browseid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    params: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_resolve.browseNavigation}
 */
proto.android_resolve.browseNavigation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_resolve.browseNavigation;
  return proto.android_resolve.browseNavigation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_resolve.browseNavigation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_resolve.browseNavigation}
 */
proto.android_resolve.browseNavigation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrowseid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_resolve.browseNavigation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_resolve.browseNavigation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_resolve.browseNavigation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.browseNavigation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrowseid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getParams();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string browseId = 2;
 * @return {string}
 */
proto.android_resolve.browseNavigation.prototype.getBrowseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_resolve.browseNavigation} returns this
 */
proto.android_resolve.browseNavigation.prototype.setBrowseid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string params = 3;
 * @return {string}
 */
proto.android_resolve.browseNavigation.prototype.getParams = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_resolve.browseNavigation} returns this
 */
proto.android_resolve.browseNavigation.prototype.setParams = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_resolve.videoNavigation.prototype.toObject = function(opt_includeInstance) {
  return proto.android_resolve.videoNavigation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_resolve.videoNavigation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.videoNavigation.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_resolve.videoNavigation}
 */
proto.android_resolve.videoNavigation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_resolve.videoNavigation;
  return proto.android_resolve.videoNavigation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_resolve.videoNavigation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_resolve.videoNavigation}
 */
proto.android_resolve.videoNavigation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_resolve.videoNavigation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_resolve.videoNavigation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_resolve.videoNavigation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.videoNavigation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.android_resolve.videoNavigation.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_resolve.videoNavigation} returns this
 */
proto.android_resolve.videoNavigation.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_resolve.searchNavigation.prototype.toObject = function(opt_includeInstance) {
  return proto.android_resolve.searchNavigation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_resolve.searchNavigation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.searchNavigation.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_resolve.searchNavigation}
 */
proto.android_resolve.searchNavigation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_resolve.searchNavigation;
  return proto.android_resolve.searchNavigation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_resolve.searchNavigation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_resolve.searchNavigation}
 */
proto.android_resolve.searchNavigation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_resolve.searchNavigation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_resolve.searchNavigation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_resolve.searchNavigation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.searchNavigation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string query = 1;
 * @return {string}
 */
proto.android_resolve.searchNavigation.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.android_resolve.searchNavigation} returns this
 */
proto.android_resolve.searchNavigation.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_resolve.root.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_resolve.root.prototype.toObject = function(opt_includeInstance) {
  return proto.android_resolve.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_resolve.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    contentList: jspb.Message.toObjectList(msg.getContentList(),
    proto.android_resolve.root.contents.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_resolve.root}
 */
proto.android_resolve.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_resolve.root;
  return proto.android_resolve.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_resolve.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_resolve.root}
 */
proto.android_resolve.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.android_resolve.root.contents;
      reader.readMessage(value,proto.android_resolve.root.contents.deserializeBinaryFromReader);
      msg.addContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_resolve.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_resolve.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_resolve.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.android_resolve.root.contents.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.android_resolve.root.contents.repeatedFields_ = [48687626,48687757,48687709];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.android_resolve.root.contents.prototype.toObject = function(opt_includeInstance) {
  return proto.android_resolve.root.contents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.android_resolve.root.contents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.root.contents.toObject = function(includeInstance, msg) {
  var f, obj = {
    browseList: jspb.Message.toObjectList(msg.getBrowseList(),
    proto.android_resolve.browseNavigation.toObject, includeInstance),
    videoList: jspb.Message.toObjectList(msg.getVideoList(),
    proto.android_resolve.videoNavigation.toObject, includeInstance),
    searchList: jspb.Message.toObjectList(msg.getSearchList(),
    proto.android_resolve.searchNavigation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.android_resolve.root.contents}
 */
proto.android_resolve.root.contents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.android_resolve.root.contents;
  return proto.android_resolve.root.contents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.android_resolve.root.contents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.android_resolve.root.contents}
 */
proto.android_resolve.root.contents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 48687626:
      var value = new proto.android_resolve.browseNavigation;
      reader.readMessage(value,proto.android_resolve.browseNavigation.deserializeBinaryFromReader);
      msg.addBrowse(value);
      break;
    case 48687757:
      var value = new proto.android_resolve.videoNavigation;
      reader.readMessage(value,proto.android_resolve.videoNavigation.deserializeBinaryFromReader);
      msg.addVideo(value);
      break;
    case 48687709:
      var value = new proto.android_resolve.searchNavigation;
      reader.readMessage(value,proto.android_resolve.searchNavigation.deserializeBinaryFromReader);
      msg.addSearch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.android_resolve.root.contents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.android_resolve.root.contents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.android_resolve.root.contents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.android_resolve.root.contents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrowseList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      48687626,
      f,
      proto.android_resolve.browseNavigation.serializeBinaryToWriter
    );
  }
  f = message.getVideoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      48687757,
      f,
      proto.android_resolve.videoNavigation.serializeBinaryToWriter
    );
  }
  f = message.getSearchList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      48687709,
      f,
      proto.android_resolve.searchNavigation.serializeBinaryToWriter
    );
  }
};


/**
 * repeated browseNavigation browse = 48687626;
 * @return {!Array<!proto.android_resolve.browseNavigation>}
 */
proto.android_resolve.root.contents.prototype.getBrowseList = function() {
  return /** @type{!Array<!proto.android_resolve.browseNavigation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_resolve.browseNavigation, 48687626));
};


/**
 * @param {!Array<!proto.android_resolve.browseNavigation>} value
 * @return {!proto.android_resolve.root.contents} returns this
*/
proto.android_resolve.root.contents.prototype.setBrowseList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 48687626, value);
};


/**
 * @param {!proto.android_resolve.browseNavigation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_resolve.browseNavigation}
 */
proto.android_resolve.root.contents.prototype.addBrowse = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 48687626, opt_value, proto.android_resolve.browseNavigation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_resolve.root.contents} returns this
 */
proto.android_resolve.root.contents.prototype.clearBrowseList = function() {
  return this.setBrowseList([]);
};


/**
 * repeated videoNavigation video = 48687757;
 * @return {!Array<!proto.android_resolve.videoNavigation>}
 */
proto.android_resolve.root.contents.prototype.getVideoList = function() {
  return /** @type{!Array<!proto.android_resolve.videoNavigation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_resolve.videoNavigation, 48687757));
};


/**
 * @param {!Array<!proto.android_resolve.videoNavigation>} value
 * @return {!proto.android_resolve.root.contents} returns this
*/
proto.android_resolve.root.contents.prototype.setVideoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 48687757, value);
};


/**
 * @param {!proto.android_resolve.videoNavigation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_resolve.videoNavigation}
 */
proto.android_resolve.root.contents.prototype.addVideo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 48687757, opt_value, proto.android_resolve.videoNavigation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_resolve.root.contents} returns this
 */
proto.android_resolve.root.contents.prototype.clearVideoList = function() {
  return this.setVideoList([]);
};


/**
 * repeated searchNavigation search = 48687709;
 * @return {!Array<!proto.android_resolve.searchNavigation>}
 */
proto.android_resolve.root.contents.prototype.getSearchList = function() {
  return /** @type{!Array<!proto.android_resolve.searchNavigation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_resolve.searchNavigation, 48687709));
};


/**
 * @param {!Array<!proto.android_resolve.searchNavigation>} value
 * @return {!proto.android_resolve.root.contents} returns this
*/
proto.android_resolve.root.contents.prototype.setSearchList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 48687709, value);
};


/**
 * @param {!proto.android_resolve.searchNavigation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_resolve.searchNavigation}
 */
proto.android_resolve.root.contents.prototype.addSearch = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 48687709, opt_value, proto.android_resolve.searchNavigation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_resolve.root.contents} returns this
 */
proto.android_resolve.root.contents.prototype.clearSearchList = function() {
  return this.setSearchList([]);
};


/**
 * repeated contents content = 2;
 * @return {!Array<!proto.android_resolve.root.contents>}
 */
proto.android_resolve.root.prototype.getContentList = function() {
  return /** @type{!Array<!proto.android_resolve.root.contents>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.android_resolve.root.contents, 2));
};


/**
 * @param {!Array<!proto.android_resolve.root.contents>} value
 * @return {!proto.android_resolve.root} returns this
*/
proto.android_resolve.root.prototype.setContentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.android_resolve.root.contents=} opt_value
 * @param {number=} opt_index
 * @return {!proto.android_resolve.root.contents}
 */
proto.android_resolve.root.prototype.addContent = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.android_resolve.root.contents, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.android_resolve.root} returns this
 */
proto.android_resolve.root.prototype.clearContentList = function() {
  return this.setContentList([]);
};


goog.object.extend(exports, proto.android_resolve);
