// source: bare_android_request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.bare_android_request.root', null, global);
goog.exportSymbol('proto.bare_android_request.root.contextType', null, global);
goog.exportSymbol('proto.bare_android_request.root.contextType.clientType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bare_android_request.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bare_android_request.root.repeatedFields_, null);
};
goog.inherits(proto.bare_android_request.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bare_android_request.root.displayName = 'proto.bare_android_request.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bare_android_request.root.contextType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bare_android_request.root.contextType.repeatedFields_, null);
};
goog.inherits(proto.bare_android_request.root.contextType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bare_android_request.root.contextType.displayName = 'proto.bare_android_request.root.contextType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bare_android_request.root.contextType.clientType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bare_android_request.root.contextType.clientType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bare_android_request.root.contextType.clientType.displayName = 'proto.bare_android_request.root.contextType.clientType';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bare_android_request.root.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bare_android_request.root.prototype.toObject = function(opt_includeInstance) {
  return proto.bare_android_request.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bare_android_request.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    contextList: jspb.Message.toObjectList(msg.getContextList(),
    proto.bare_android_request.root.contextType.toObject, includeInstance),
    browseid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bare_android_request.root}
 */
proto.bare_android_request.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bare_android_request.root;
  return proto.bare_android_request.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bare_android_request.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bare_android_request.root}
 */
proto.bare_android_request.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bare_android_request.root.contextType;
      reader.readMessage(value,proto.bare_android_request.root.contextType.deserializeBinaryFromReader);
      msg.addContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrowseid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bare_android_request.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bare_android_request.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bare_android_request.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContextList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bare_android_request.root.contextType.serializeBinaryToWriter
    );
  }
  f = message.getBrowseid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bare_android_request.root.contextType.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bare_android_request.root.contextType.prototype.toObject = function(opt_includeInstance) {
  return proto.bare_android_request.root.contextType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bare_android_request.root.contextType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.contextType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientList: jspb.Message.toObjectList(msg.getClientList(),
    proto.bare_android_request.root.contextType.clientType.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bare_android_request.root.contextType}
 */
proto.bare_android_request.root.contextType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bare_android_request.root.contextType;
  return proto.bare_android_request.root.contextType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bare_android_request.root.contextType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bare_android_request.root.contextType}
 */
proto.bare_android_request.root.contextType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.bare_android_request.root.contextType.clientType;
      reader.readMessage(value,proto.bare_android_request.root.contextType.clientType.deserializeBinaryFromReader);
      msg.addClient(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bare_android_request.root.contextType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bare_android_request.root.contextType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bare_android_request.root.contextType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.contextType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.bare_android_request.root.contextType.clientType.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bare_android_request.root.contextType.clientType.prototype.toObject = function(opt_includeInstance) {
  return proto.bare_android_request.root.contextType.clientType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bare_android_request.root.contextType.clientType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.contextType.clientType.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientnumber: jspb.Message.getFieldWithDefault(msg, 16, 0),
    clientversion: jspb.Message.getFieldWithDefault(msg, 17, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bare_android_request.root.contextType.clientType}
 */
proto.bare_android_request.root.contextType.clientType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bare_android_request.root.contextType.clientType;
  return proto.bare_android_request.root.contextType.clientType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bare_android_request.root.contextType.clientType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bare_android_request.root.contextType.clientType}
 */
proto.bare_android_request.root.contextType.clientType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientnumber(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bare_android_request.root.contextType.clientType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bare_android_request.root.contextType.clientType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bare_android_request.root.contextType.clientType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bare_android_request.root.contextType.clientType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientnumber();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getClientversion();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
};


/**
 * optional int32 clientNumber = 16;
 * @return {number}
 */
proto.bare_android_request.root.contextType.clientType.prototype.getClientnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.bare_android_request.root.contextType.clientType} returns this
 */
proto.bare_android_request.root.contextType.clientType.prototype.setClientnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string clientVersion = 17;
 * @return {string}
 */
proto.bare_android_request.root.contextType.clientType.prototype.getClientversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.bare_android_request.root.contextType.clientType} returns this
 */
proto.bare_android_request.root.contextType.clientType.prototype.setClientversion = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * repeated clientType client = 1;
 * @return {!Array<!proto.bare_android_request.root.contextType.clientType>}
 */
proto.bare_android_request.root.contextType.prototype.getClientList = function() {
  return /** @type{!Array<!proto.bare_android_request.root.contextType.clientType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bare_android_request.root.contextType.clientType, 1));
};


/**
 * @param {!Array<!proto.bare_android_request.root.contextType.clientType>} value
 * @return {!proto.bare_android_request.root.contextType} returns this
*/
proto.bare_android_request.root.contextType.prototype.setClientList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bare_android_request.root.contextType.clientType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bare_android_request.root.contextType.clientType}
 */
proto.bare_android_request.root.contextType.prototype.addClient = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bare_android_request.root.contextType.clientType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bare_android_request.root.contextType} returns this
 */
proto.bare_android_request.root.contextType.prototype.clearClientList = function() {
  return this.setClientList([]);
};


/**
 * repeated contextType context = 1;
 * @return {!Array<!proto.bare_android_request.root.contextType>}
 */
proto.bare_android_request.root.prototype.getContextList = function() {
  return /** @type{!Array<!proto.bare_android_request.root.contextType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.bare_android_request.root.contextType, 1));
};


/**
 * @param {!Array<!proto.bare_android_request.root.contextType>} value
 * @return {!proto.bare_android_request.root} returns this
*/
proto.bare_android_request.root.prototype.setContextList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bare_android_request.root.contextType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bare_android_request.root.contextType}
 */
proto.bare_android_request.root.prototype.addContext = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bare_android_request.root.contextType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bare_android_request.root} returns this
 */
proto.bare_android_request.root.prototype.clearContextList = function() {
  return this.setContextList([]);
};


/**
 * optional string browseId = 2;
 * @return {string}
 */
proto.bare_android_request.root.prototype.getBrowseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bare_android_request.root} returns this
 */
proto.bare_android_request.root.prototype.setBrowseid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.bare_android_request);
