// source: community_tab_request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.community_tab_request.root', null, global);
goog.exportSymbol('proto.community_tab_request.root.container', null, global);
goog.exportSymbol('proto.community_tab_request.runs', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.community_tab_request.runs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.community_tab_request.runs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.community_tab_request.runs.displayName = 'proto.community_tab_request.runs';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.community_tab_request.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.community_tab_request.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.community_tab_request.root.displayName = 'proto.community_tab_request.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.community_tab_request.root.container = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.community_tab_request.root.container, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.community_tab_request.root.container.displayName = 'proto.community_tab_request.root.container';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.community_tab_request.runs.prototype.toObject = function(opt_includeInstance) {
  return proto.community_tab_request.runs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.community_tab_request.runs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.runs.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.community_tab_request.runs}
 */
proto.community_tab_request.runs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.community_tab_request.runs;
  return proto.community_tab_request.runs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.community_tab_request.runs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.community_tab_request.runs}
 */
proto.community_tab_request.runs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.community_tab_request.runs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.community_tab_request.runs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.community_tab_request.runs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.runs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.community_tab_request.runs.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.community_tab_request.runs} returns this
 */
proto.community_tab_request.runs.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.community_tab_request.root.prototype.toObject = function(opt_includeInstance) {
  return proto.community_tab_request.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.community_tab_request.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    contain: (f = msg.getContain()) && proto.community_tab_request.root.container.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.community_tab_request.root}
 */
proto.community_tab_request.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.community_tab_request.root;
  return proto.community_tab_request.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.community_tab_request.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.community_tab_request.root}
 */
proto.community_tab_request.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 152:
      var value = new proto.community_tab_request.root.container;
      reader.readMessage(value,proto.community_tab_request.root.container.deserializeBinaryFromReader);
      msg.setContain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.community_tab_request.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.community_tab_request.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.community_tab_request.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContain();
  if (f != null) {
    writer.writeMessage(
      152,
      f,
      proto.community_tab_request.root.container.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.community_tab_request.root.container.prototype.toObject = function(opt_includeInstance) {
  return proto.community_tab_request.root.container.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.community_tab_request.root.container} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.root.container.toObject = function(includeInstance, msg) {
  var f, obj = {
    browseid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    param: (f = msg.getParam()) && proto.community_tab_request.runs.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.community_tab_request.root.container}
 */
proto.community_tab_request.root.container.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.community_tab_request.root.container;
  return proto.community_tab_request.root.container.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.community_tab_request.root.container} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.community_tab_request.root.container}
 */
proto.community_tab_request.root.container.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrowseid(value);
      break;
    case 2:
      var value = new proto.community_tab_request.runs;
      reader.readMessage(value,proto.community_tab_request.runs.deserializeBinaryFromReader);
      msg.setParam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.community_tab_request.root.container.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.community_tab_request.root.container.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.community_tab_request.root.container} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.community_tab_request.root.container.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrowseid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParam();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.community_tab_request.runs.serializeBinaryToWriter
    );
  }
};


/**
 * optional string browseId = 1;
 * @return {string}
 */
proto.community_tab_request.root.container.prototype.getBrowseid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.community_tab_request.root.container} returns this
 */
proto.community_tab_request.root.container.prototype.setBrowseid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional runs param = 2;
 * @return {?proto.community_tab_request.runs}
 */
proto.community_tab_request.root.container.prototype.getParam = function() {
  return /** @type{?proto.community_tab_request.runs} */ (
    jspb.Message.getWrapperField(this, proto.community_tab_request.runs, 2));
};


/**
 * @param {?proto.community_tab_request.runs|undefined} value
 * @return {!proto.community_tab_request.root.container} returns this
*/
proto.community_tab_request.root.container.prototype.setParam = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.community_tab_request.root.container} returns this
 */
proto.community_tab_request.root.container.prototype.clearParam = function() {
  return this.setParam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.community_tab_request.root.container.prototype.hasParam = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional container contain = 152;
 * @return {?proto.community_tab_request.root.container}
 */
proto.community_tab_request.root.prototype.getContain = function() {
  return /** @type{?proto.community_tab_request.root.container} */ (
    jspb.Message.getWrapperField(this, proto.community_tab_request.root.container, 152));
};


/**
 * @param {?proto.community_tab_request.root.container|undefined} value
 * @return {!proto.community_tab_request.root} returns this
*/
proto.community_tab_request.root.prototype.setContain = function(value) {
  return jspb.Message.setWrapperField(this, 152, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.community_tab_request.root} returns this
 */
proto.community_tab_request.root.prototype.clearContain = function() {
  return this.setContain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.community_tab_request.root.prototype.hasContain = function() {
  return jspb.Message.getField(this, 152) != null;
};


goog.object.extend(exports, proto.community_tab_request);
