// source: create_comment.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.create_comment_request.root', null, global);
goog.exportSymbol('proto.create_comment_request.root.zeroMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.create_comment_request.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.create_comment_request.root.repeatedFields_, null);
};
goog.inherits(proto.create_comment_request.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.create_comment_request.root.displayName = 'proto.create_comment_request.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.create_comment_request.root.zeroMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.create_comment_request.root.zeroMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.create_comment_request.root.zeroMsg.displayName = 'proto.create_comment_request.root.zeroMsg';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.create_comment_request.root.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.create_comment_request.root.prototype.toObject = function(opt_includeInstance) {
  return proto.create_comment_request.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.create_comment_request.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.create_comment_request.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    videoid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fivemsgList: jspb.Message.toObjectList(msg.getFivemsgList(),
    proto.create_comment_request.root.zeroMsg.toObject, includeInstance),
    sevenint: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.create_comment_request.root}
 */
proto.create_comment_request.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.create_comment_request.root;
  return proto.create_comment_request.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.create_comment_request.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.create_comment_request.root}
 */
proto.create_comment_request.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideoid(value);
      break;
    case 5:
      var value = new proto.create_comment_request.root.zeroMsg;
      reader.readMessage(value,proto.create_comment_request.root.zeroMsg.deserializeBinaryFromReader);
      msg.addFivemsg(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSevenint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.create_comment_request.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.create_comment_request.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.create_comment_request.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.create_comment_request.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVideoid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFivemsgList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.create_comment_request.root.zeroMsg.serializeBinaryToWriter
    );
  }
  f = message.getSevenint();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.create_comment_request.root.zeroMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.create_comment_request.root.zeroMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.create_comment_request.root.zeroMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.create_comment_request.root.zeroMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    zeroint: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.create_comment_request.root.zeroMsg}
 */
proto.create_comment_request.root.zeroMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.create_comment_request.root.zeroMsg;
  return proto.create_comment_request.root.zeroMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.create_comment_request.root.zeroMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.create_comment_request.root.zeroMsg}
 */
proto.create_comment_request.root.zeroMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setZeroint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.create_comment_request.root.zeroMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.create_comment_request.root.zeroMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.create_comment_request.root.zeroMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.create_comment_request.root.zeroMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getZeroint();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 zeroInt = 1;
 * @return {number}
 */
proto.create_comment_request.root.zeroMsg.prototype.getZeroint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.create_comment_request.root.zeroMsg} returns this
 */
proto.create_comment_request.root.zeroMsg.prototype.setZeroint = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string videoId = 2;
 * @return {string}
 */
proto.create_comment_request.root.prototype.getVideoid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.create_comment_request.root} returns this
 */
proto.create_comment_request.root.prototype.setVideoid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated zeroMsg fiveMsg = 5;
 * @return {!Array<!proto.create_comment_request.root.zeroMsg>}
 */
proto.create_comment_request.root.prototype.getFivemsgList = function() {
  return /** @type{!Array<!proto.create_comment_request.root.zeroMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.create_comment_request.root.zeroMsg, 5));
};


/**
 * @param {!Array<!proto.create_comment_request.root.zeroMsg>} value
 * @return {!proto.create_comment_request.root} returns this
*/
proto.create_comment_request.root.prototype.setFivemsgList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.create_comment_request.root.zeroMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.create_comment_request.root.zeroMsg}
 */
proto.create_comment_request.root.prototype.addFivemsg = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.create_comment_request.root.zeroMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.create_comment_request.root} returns this
 */
proto.create_comment_request.root.prototype.clearFivemsgList = function() {
  return this.setFivemsgList([]);
};


/**
 * optional int64 sevenInt = 10;
 * @return {number}
 */
proto.create_comment_request.root.prototype.getSevenint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.create_comment_request.root} returns this
 */
proto.create_comment_request.root.prototype.setSevenint = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


goog.object.extend(exports, proto.create_comment_request);
