// source: creator_request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.creator_request.chipRender', null, global);
goog.exportSymbol('proto.creator_request.chipRender.contents', null, global);
goog.exportSymbol('proto.creator_request.chipRender.run', null, global);
goog.exportSymbol('proto.creator_request.communityDetailParams', null, global);
goog.exportSymbol('proto.creator_request.creatorChipConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.creator_request.chipRender = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.creator_request.chipRender, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.creator_request.chipRender.displayName = 'proto.creator_request.chipRender';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.creator_request.chipRender.run = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.creator_request.chipRender.run, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.creator_request.chipRender.run.displayName = 'proto.creator_request.chipRender.run';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.creator_request.chipRender.contents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.creator_request.chipRender.contents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.creator_request.chipRender.contents.displayName = 'proto.creator_request.chipRender.contents';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.creator_request.creatorChipConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.creator_request.creatorChipConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.creator_request.creatorChipConfig.displayName = 'proto.creator_request.creatorChipConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.creator_request.communityDetailParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.creator_request.communityDetailParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.creator_request.communityDetailParams.displayName = 'proto.creator_request.communityDetailParams';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.creator_request.chipRender.prototype.toObject = function(opt_includeInstance) {
  return proto.creator_request.chipRender.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.creator_request.chipRender} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.toObject = function(includeInstance, msg) {
  var f, obj = {
    content: (f = msg.getContent()) && proto.creator_request.chipRender.contents.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.creator_request.chipRender}
 */
proto.creator_request.chipRender.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.creator_request.chipRender;
  return proto.creator_request.chipRender.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.creator_request.chipRender} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.creator_request.chipRender}
 */
proto.creator_request.chipRender.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.creator_request.chipRender.contents;
      reader.readMessage(value,proto.creator_request.chipRender.contents.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.creator_request.chipRender.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.creator_request.chipRender.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.creator_request.chipRender} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.creator_request.chipRender.contents.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.creator_request.chipRender.run.prototype.toObject = function(opt_includeInstance) {
  return proto.creator_request.chipRender.run.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.creator_request.chipRender.run} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.run.toObject = function(includeInstance, msg) {
  var f, obj = {
    videoid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    channelid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.creator_request.chipRender.run}
 */
proto.creator_request.chipRender.run.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.creator_request.chipRender.run;
  return proto.creator_request.chipRender.run.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.creator_request.chipRender.run} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.creator_request.chipRender.run}
 */
proto.creator_request.chipRender.run.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideoid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.creator_request.chipRender.run.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.creator_request.chipRender.run.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.creator_request.chipRender.run} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.run.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVideoid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string videoId = 1;
 * @return {string}
 */
proto.creator_request.chipRender.run.prototype.getVideoid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.creator_request.chipRender.run} returns this
 */
proto.creator_request.chipRender.run.prototype.setVideoid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string channelId = 2;
 * @return {string}
 */
proto.creator_request.chipRender.run.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.creator_request.chipRender.run} returns this
 */
proto.creator_request.chipRender.run.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.creator_request.chipRender.contents.prototype.toObject = function(opt_includeInstance) {
  return proto.creator_request.chipRender.contents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.creator_request.chipRender.contents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.contents.toObject = function(includeInstance, msg) {
  var f, obj = {
    relcurrenttime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    channelid: (f = msg.getChannelid()) && proto.creator_request.chipRender.run.toObject(includeInstance, f),
    timeid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.creator_request.chipRender.contents}
 */
proto.creator_request.chipRender.contents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.creator_request.chipRender.contents;
  return proto.creator_request.chipRender.contents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.creator_request.chipRender.contents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.creator_request.chipRender.contents}
 */
proto.creator_request.chipRender.contents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelcurrenttime(value);
      break;
    case 2:
      var value = new proto.creator_request.chipRender.run;
      reader.readMessage(value,proto.creator_request.chipRender.run.deserializeBinaryFromReader);
      msg.setChannelid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimeid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.creator_request.chipRender.contents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.creator_request.chipRender.contents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.creator_request.chipRender.contents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.chipRender.contents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRelcurrenttime();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getChannelid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.creator_request.chipRender.run.serializeBinaryToWriter
    );
  }
  f = message.getTimeid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 relCurrentTime = 1;
 * @return {number}
 */
proto.creator_request.chipRender.contents.prototype.getRelcurrenttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.creator_request.chipRender.contents} returns this
 */
proto.creator_request.chipRender.contents.prototype.setRelcurrenttime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional run channelId = 2;
 * @return {?proto.creator_request.chipRender.run}
 */
proto.creator_request.chipRender.contents.prototype.getChannelid = function() {
  return /** @type{?proto.creator_request.chipRender.run} */ (
    jspb.Message.getWrapperField(this, proto.creator_request.chipRender.run, 2));
};


/**
 * @param {?proto.creator_request.chipRender.run|undefined} value
 * @return {!proto.creator_request.chipRender.contents} returns this
*/
proto.creator_request.chipRender.contents.prototype.setChannelid = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.creator_request.chipRender.contents} returns this
 */
proto.creator_request.chipRender.contents.prototype.clearChannelid = function() {
  return this.setChannelid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.creator_request.chipRender.contents.prototype.hasChannelid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 timeId = 3;
 * @return {number}
 */
proto.creator_request.chipRender.contents.prototype.getTimeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.creator_request.chipRender.contents} returns this
 */
proto.creator_request.chipRender.contents.prototype.setTimeid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional contents content = 1;
 * @return {?proto.creator_request.chipRender.contents}
 */
proto.creator_request.chipRender.prototype.getContent = function() {
  return /** @type{?proto.creator_request.chipRender.contents} */ (
    jspb.Message.getWrapperField(this, proto.creator_request.chipRender.contents, 1));
};


/**
 * @param {?proto.creator_request.chipRender.contents|undefined} value
 * @return {!proto.creator_request.chipRender} returns this
*/
proto.creator_request.chipRender.prototype.setContent = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.creator_request.chipRender} returns this
 */
proto.creator_request.chipRender.prototype.clearContent = function() {
  return this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.creator_request.chipRender.prototype.hasContent = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.creator_request.creatorChipConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.creator_request.creatorChipConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.creator_request.creatorChipConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.creatorChipConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    chip: (f = msg.getChip()) && proto.creator_request.chipRender.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.creator_request.creatorChipConfig}
 */
proto.creator_request.creatorChipConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.creator_request.creatorChipConfig;
  return proto.creator_request.creatorChipConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.creator_request.creatorChipConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.creator_request.creatorChipConfig}
 */
proto.creator_request.creatorChipConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 502358640:
      var value = new proto.creator_request.chipRender;
      reader.readMessage(value,proto.creator_request.chipRender.deserializeBinaryFromReader);
      msg.setChip(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.creator_request.creatorChipConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.creator_request.creatorChipConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.creator_request.creatorChipConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.creatorChipConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChip();
  if (f != null) {
    writer.writeMessage(
      502358640,
      f,
      proto.creator_request.chipRender.serializeBinaryToWriter
    );
  }
};


/**
 * optional chipRender chip = 502358640;
 * @return {?proto.creator_request.chipRender}
 */
proto.creator_request.creatorChipConfig.prototype.getChip = function() {
  return /** @type{?proto.creator_request.chipRender} */ (
    jspb.Message.getWrapperField(this, proto.creator_request.chipRender, 502358640));
};


/**
 * @param {?proto.creator_request.chipRender|undefined} value
 * @return {!proto.creator_request.creatorChipConfig} returns this
*/
proto.creator_request.creatorChipConfig.prototype.setChip = function(value) {
  return jspb.Message.setWrapperField(this, 502358640, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.creator_request.creatorChipConfig} returns this
 */
proto.creator_request.creatorChipConfig.prototype.clearChip = function() {
  return this.setChip(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.creator_request.creatorChipConfig.prototype.hasChip = function() {
  return jspb.Message.getField(this, 502358640) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.creator_request.communityDetailParams.prototype.toObject = function(opt_includeInstance) {
  return proto.creator_request.communityDetailParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.creator_request.communityDetailParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.communityDetailParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    channelid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.creator_request.communityDetailParams}
 */
proto.creator_request.communityDetailParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.creator_request.communityDetailParams;
  return proto.creator_request.communityDetailParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.creator_request.communityDetailParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.creator_request.communityDetailParams}
 */
proto.creator_request.communityDetailParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRequestid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.creator_request.communityDetailParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.creator_request.communityDetailParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.creator_request.communityDetailParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.creator_request.communityDetailParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 requestId = 2;
 * @return {number}
 */
proto.creator_request.communityDetailParams.prototype.getRequestid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.creator_request.communityDetailParams} returns this
 */
proto.creator_request.communityDetailParams.prototype.setRequestid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string channelId = 3;
 * @return {string}
 */
proto.creator_request.communityDetailParams.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.creator_request.communityDetailParams} returns this
 */
proto.creator_request.communityDetailParams.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.creator_request);
