// source: onesie.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.onesie_request.clientMsg', null, global);
goog.exportSymbol('proto.onesie_request.part11Resp', null, global);
goog.exportSymbol('proto.onesie_request.playerReq', null, global);
goog.exportSymbol('proto.onesie_request.request', null, global);
goog.exportSymbol('proto.onesie_request.requestHeader', null, global);
goog.exportSymbol('proto.onesie_request.root', null, global);
goog.exportSymbol('proto.onesie_request.timingData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.requestHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onesie_request.requestHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.requestHeader.displayName = 'proto.onesie_request.requestHeader';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.playerReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.onesie_request.playerReq.repeatedFields_, null);
};
goog.inherits(proto.onesie_request.playerReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.playerReq.displayName = 'proto.onesie_request.playerReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.timingData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onesie_request.timingData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.timingData.displayName = 'proto.onesie_request.timingData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.clientMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onesie_request.clientMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.clientMsg.displayName = 'proto.onesie_request.clientMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onesie_request.request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.request.displayName = 'proto.onesie_request.request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.onesie_request.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.root.displayName = 'proto.onesie_request.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.onesie_request.part11Resp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.onesie_request.part11Resp.repeatedFields_, null);
};
goog.inherits(proto.onesie_request.part11Resp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.onesie_request.part11Resp.displayName = 'proto.onesie_request.part11Resp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.requestHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.requestHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.requestHeader} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.requestHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.requestHeader}
 */
proto.onesie_request.requestHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.requestHeader;
  return proto.onesie_request.requestHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.requestHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.requestHeader}
 */
proto.onesie_request.requestHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.requestHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.requestHeader.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.requestHeader} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.requestHeader.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.onesie_request.requestHeader.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.requestHeader} returns this
 */
proto.onesie_request.requestHeader.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.onesie_request.requestHeader.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.requestHeader} returns this
 */
proto.onesie_request.requestHeader.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.onesie_request.playerReq.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.playerReq.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.playerReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.playerReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.playerReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    headerList: jspb.Message.toObjectList(msg.getHeaderList(),
    proto.onesie_request.requestHeader.toObject, includeInstance),
    requestbody: jspb.Message.getFieldWithDefault(msg, 3, ""),
    useproxydeprecated: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    five: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    skipencrypt: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    seven: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    eight: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    nine: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    ten: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    eleven: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    twelve: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    thirteen: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    fourteen: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    fifteen: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
    sixteen: jspb.Message.getBooleanFieldWithDefault(msg, 16, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.playerReq}
 */
proto.onesie_request.playerReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.playerReq;
  return proto.onesie_request.playerReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.playerReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.playerReq}
 */
proto.onesie_request.playerReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = new proto.onesie_request.requestHeader;
      reader.readMessage(value,proto.onesie_request.requestHeader.deserializeBinaryFromReader);
      msg.addHeader(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestbody(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUseproxydeprecated(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFive(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSkipencrypt(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSeven(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEight(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNine(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTen(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEleven(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTwelve(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setThirteen(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFourteen(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFifteen(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSixteen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.playerReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.playerReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.playerReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.playerReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHeaderList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.onesie_request.requestHeader.serializeBinaryToWriter
    );
  }
  f = message.getRequestbody();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUseproxydeprecated();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getFive();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getSkipencrypt();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getSeven();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getEight();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getNine();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getTen();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getEleven();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getTwelve();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getThirteen();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getFourteen();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getFifteen();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getSixteen();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.onesie_request.playerReq.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated requestHeader header = 2;
 * @return {!Array<!proto.onesie_request.requestHeader>}
 */
proto.onesie_request.playerReq.prototype.getHeaderList = function() {
  return /** @type{!Array<!proto.onesie_request.requestHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.onesie_request.requestHeader, 2));
};


/**
 * @param {!Array<!proto.onesie_request.requestHeader>} value
 * @return {!proto.onesie_request.playerReq} returns this
*/
proto.onesie_request.playerReq.prototype.setHeaderList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.onesie_request.requestHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.onesie_request.requestHeader}
 */
proto.onesie_request.playerReq.prototype.addHeader = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.onesie_request.requestHeader, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.clearHeaderList = function() {
  return this.setHeaderList([]);
};


/**
 * optional string requestBody = 3;
 * @return {string}
 */
proto.onesie_request.playerReq.prototype.getRequestbody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setRequestbody = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool useProxyDeprecated = 4;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getUseproxydeprecated = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setUseproxydeprecated = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool five = 5;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getFive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setFive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool skipEncrypt = 6;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getSkipencrypt = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setSkipencrypt = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool seven = 7;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getSeven = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setSeven = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool eight = 8;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getEight = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setEight = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool nine = 9;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getNine = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setNine = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool ten = 10;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getTen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setTen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool eleven = 11;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getEleven = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setEleven = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool twelve = 12;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getTwelve = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setTwelve = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool thirteen = 13;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getThirteen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setThirteen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional bool fourteen = 14;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getFourteen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setFourteen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool fifteen = 15;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getFifteen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setFifteen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool sixteen = 16;
 * @return {boolean}
 */
proto.onesie_request.playerReq.prototype.getSixteen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.playerReq} returns this
 */
proto.onesie_request.playerReq.prototype.setSixteen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.timingData.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.timingData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.timingData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.timingData.toObject = function(includeInstance, msg) {
  var f, obj = {
    absinittime: jspb.Message.getFieldWithDefault(msg, 13, 0),
    videoheight: jspb.Message.getFieldWithDefault(msg, 16, 0),
    playerwidth: jspb.Message.getFieldWithDefault(msg, 18, 0),
    playerheight: jspb.Message.getFieldWithDefault(msg, 19, 0),
    fiveint: jspb.Message.getFieldWithDefault(msg, 27, 0),
    starttime: jspb.Message.getFieldWithDefault(msg, 28, 0),
    reqinittime: jspb.Message.getFieldWithDefault(msg, 29, 0),
    fiveint2: jspb.Message.getFieldWithDefault(msg, 34, 0),
    relinittime: jspb.Message.getFieldWithDefault(msg, 36, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.timingData}
 */
proto.onesie_request.timingData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.timingData;
  return proto.onesie_request.timingData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.timingData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.timingData}
 */
proto.onesie_request.timingData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAbsinittime(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVideoheight(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerwidth(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerheight(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFiveint(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStarttime(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReqinittime(value);
      break;
    case 34:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFiveint2(value);
      break;
    case 36:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelinittime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.timingData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.timingData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.timingData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.timingData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAbsinittime();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getVideoheight();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getPlayerwidth();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getPlayerheight();
  if (f !== 0) {
    writer.writeInt32(
      19,
      f
    );
  }
  f = message.getFiveint();
  if (f !== 0) {
    writer.writeInt32(
      27,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 28));
  if (f != null) {
    writer.writeInt32(
      28,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 29));
  if (f != null) {
    writer.writeInt32(
      29,
      f
    );
  }
  f = message.getFiveint2();
  if (f !== 0) {
    writer.writeInt32(
      34,
      f
    );
  }
  f = message.getRelinittime();
  if (f !== 0) {
    writer.writeInt32(
      36,
      f
    );
  }
};


/**
 * optional int32 absInitTime = 13;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getAbsinittime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setAbsinittime = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 videoHeight = 16;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getVideoheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setVideoheight = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional int32 playerWidth = 18;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getPlayerwidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setPlayerwidth = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional int32 playerHeight = 19;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getPlayerheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setPlayerheight = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional int32 fiveInt = 27;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getFiveint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setFiveint = function(value) {
  return jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional int32 startTime = 28;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getStarttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setStarttime = function(value) {
  return jspb.Message.setField(this, 28, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.clearStarttime = function() {
  return jspb.Message.setField(this, 28, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.timingData.prototype.hasStarttime = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional int32 reqInitTime = 29;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getReqinittime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 29, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setReqinittime = function(value) {
  return jspb.Message.setField(this, 29, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.clearReqinittime = function() {
  return jspb.Message.setField(this, 29, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.timingData.prototype.hasReqinittime = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional int32 fiveInt2 = 34;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getFiveint2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 34, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setFiveint2 = function(value) {
  return jspb.Message.setProto3IntField(this, 34, value);
};


/**
 * optional int32 relInitTime = 36;
 * @return {number}
 */
proto.onesie_request.timingData.prototype.getRelinittime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 36, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.timingData} returns this
 */
proto.onesie_request.timingData.prototype.setRelinittime = function(value) {
  return jspb.Message.setProto3IntField(this, 36, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.clientMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.clientMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.clientMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.clientMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    devicemake: jspb.Message.getFieldWithDefault(msg, 12, ""),
    devicemodel: jspb.Message.getFieldWithDefault(msg, 13, ""),
    clientnumber: jspb.Message.getFieldWithDefault(msg, 16, 0),
    clientversion: jspb.Message.getFieldWithDefault(msg, 17, ""),
    osname: jspb.Message.getFieldWithDefault(msg, 18, ""),
    osversion: jspb.Message.getFieldWithDefault(msg, 19, ""),
    locale: jspb.Message.getFieldWithDefault(msg, 21, ""),
    gl: jspb.Message.getFieldWithDefault(msg, 22, ""),
    plreq: jspb.Message.getFieldWithDefault(msg, 25, ""),
    screenwidth: jspb.Message.getFieldWithDefault(msg, 37, 0),
    screenheight: jspb.Message.getFieldWithDefault(msg, 38, 0),
    screenwidth2: jspb.Message.getFieldWithDefault(msg, 55, 0),
    screenheight2: jspb.Message.getFieldWithDefault(msg, 56, 0),
    utcoffsetminutes: jspb.Message.getFieldWithDefault(msg, 67, 0),
    timezone: jspb.Message.getFieldWithDefault(msg, 80, ""),
    devicecodename: jspb.Message.getFieldWithDefault(msg, 92, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.clientMsg}
 */
proto.onesie_request.clientMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.clientMsg;
  return proto.onesie_request.clientMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.clientMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.clientMsg}
 */
proto.onesie_request.clientMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicemake(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicemodel(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientnumber(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientversion(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsname(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsversion(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocale(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setGl(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlreq(value);
      break;
    case 37:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenwidth(value);
      break;
    case 38:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenheight(value);
      break;
    case 55:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenwidth2(value);
      break;
    case 56:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenheight2(value);
      break;
    case 67:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUtcoffsetminutes(value);
      break;
    case 80:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimezone(value);
      break;
    case 92:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicecodename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.clientMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.clientMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.clientMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.clientMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevicemake();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getDevicemodel();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getClientnumber();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getClientversion();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getOsname();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getOsversion();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getLocale();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getGl();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getPlreq();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getScreenwidth();
  if (f !== 0) {
    writer.writeInt32(
      37,
      f
    );
  }
  f = message.getScreenheight();
  if (f !== 0) {
    writer.writeInt32(
      38,
      f
    );
  }
  f = message.getScreenwidth2();
  if (f !== 0) {
    writer.writeInt32(
      55,
      f
    );
  }
  f = message.getScreenheight2();
  if (f !== 0) {
    writer.writeInt32(
      56,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 67));
  if (f != null) {
    writer.writeInt32(
      67,
      f
    );
  }
  f = message.getTimezone();
  if (f.length > 0) {
    writer.writeString(
      80,
      f
    );
  }
  f = message.getDevicecodename();
  if (f.length > 0) {
    writer.writeString(
      92,
      f
    );
  }
};


/**
 * optional string deviceMake = 12;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getDevicemake = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setDevicemake = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string deviceModel = 13;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getDevicemodel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setDevicemodel = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int32 clientNumber = 16;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getClientnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setClientnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string clientVersion = 17;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getClientversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setClientversion = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string osName = 18;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getOsname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setOsname = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string osVersion = 19;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getOsversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setOsversion = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string locale = 21;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getLocale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setLocale = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string gl = 22;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getGl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setGl = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string plreq = 25;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getPlreq = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setPlreq = function(value) {
  return jspb.Message.setProto3StringField(this, 25, value);
};


/**
 * optional int32 screenWidth = 37;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getScreenwidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 37, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setScreenwidth = function(value) {
  return jspb.Message.setProto3IntField(this, 37, value);
};


/**
 * optional int32 screenHeight = 38;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getScreenheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 38, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setScreenheight = function(value) {
  return jspb.Message.setProto3IntField(this, 38, value);
};


/**
 * optional int32 screenWidth2 = 55;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getScreenwidth2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 55, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setScreenwidth2 = function(value) {
  return jspb.Message.setProto3IntField(this, 55, value);
};


/**
 * optional int32 screenHeight2 = 56;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getScreenheight2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 56, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setScreenheight2 = function(value) {
  return jspb.Message.setProto3IntField(this, 56, value);
};


/**
 * optional int32 utcOffsetMinutes = 67;
 * @return {number}
 */
proto.onesie_request.clientMsg.prototype.getUtcoffsetminutes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 67, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setUtcoffsetminutes = function(value) {
  return jspb.Message.setField(this, 67, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.clearUtcoffsetminutes = function() {
  return jspb.Message.setField(this, 67, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.clientMsg.prototype.hasUtcoffsetminutes = function() {
  return jspb.Message.getField(this, 67) != null;
};


/**
 * optional string timeZone = 80;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getTimezone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 80, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setTimezone = function(value) {
  return jspb.Message.setProto3StringField(this, 80, value);
};


/**
 * optional string deviceCodename = 92;
 * @return {string}
 */
proto.onesie_request.clientMsg.prototype.getDevicecodename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 92, ""));
};


/**
 * @param {string} value
 * @return {!proto.onesie_request.clientMsg} returns this
 */
proto.onesie_request.clientMsg.prototype.setDevicecodename = function(value) {
  return jspb.Message.setProto3StringField(this, 92, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.request.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.request.toObject = function(includeInstance, msg) {
  var f, obj = {
    encryptedclientkey: msg.getEncryptedclientkey_asB64(),
    ten: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    thirteenint: jspb.Message.getFieldWithDefault(msg, 13, 0),
    fourteenint: jspb.Message.getFieldWithDefault(msg, 14, 0),
    req: (f = msg.getReq()) && proto.onesie_request.playerReq.toObject(includeInstance, f),
    seventeenint: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.request}
 */
proto.onesie_request.request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.request;
  return proto.onesie_request.request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.request}
 */
proto.onesie_request.request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncryptedclientkey(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTen(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setThirteenint(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFourteenint(value);
      break;
    case 16:
      var value = new proto.onesie_request.playerReq;
      reader.readMessage(value,proto.onesie_request.playerReq.deserializeBinaryFromReader);
      msg.setReq(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeventeenint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncryptedclientkey_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getTen();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getReq();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.onesie_request.playerReq.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeInt32(
      17,
      f
    );
  }
};


/**
 * optional bytes encryptedClientKey = 5;
 * @return {!(string|Uint8Array)}
 */
proto.onesie_request.request.prototype.getEncryptedclientkey = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes encryptedClientKey = 5;
 * This is a type-conversion wrapper around `getEncryptedclientkey()`
 * @return {string}
 */
proto.onesie_request.request.prototype.getEncryptedclientkey_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncryptedclientkey()));
};


/**
 * optional bytes encryptedClientKey = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncryptedclientkey()`
 * @return {!Uint8Array}
 */
proto.onesie_request.request.prototype.getEncryptedclientkey_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncryptedclientkey()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.setEncryptedclientkey = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional bool ten = 10;
 * @return {boolean}
 */
proto.onesie_request.request.prototype.getTen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.setTen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional int32 thirteenint = 13;
 * @return {number}
 */
proto.onesie_request.request.prototype.getThirteenint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.setThirteenint = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.clearThirteenint = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.request.prototype.hasThirteenint = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional int32 fourteenint = 14;
 * @return {number}
 */
proto.onesie_request.request.prototype.getFourteenint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.setFourteenint = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.clearFourteenint = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.request.prototype.hasFourteenint = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional playerReq req = 16;
 * @return {?proto.onesie_request.playerReq}
 */
proto.onesie_request.request.prototype.getReq = function() {
  return /** @type{?proto.onesie_request.playerReq} */ (
    jspb.Message.getWrapperField(this, proto.onesie_request.playerReq, 16));
};


/**
 * @param {?proto.onesie_request.playerReq|undefined} value
 * @return {!proto.onesie_request.request} returns this
*/
proto.onesie_request.request.prototype.setReq = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.clearReq = function() {
  return this.setReq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.request.prototype.hasReq = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional int32 seventeenint = 17;
 * @return {number}
 */
proto.onesie_request.request.prototype.getSeventeenint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.setSeventeenint = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.request} returns this
 */
proto.onesie_request.request.prototype.clearSeventeenint = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.request.prototype.hasSeventeenint = function() {
  return jspb.Message.getField(this, 17) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.root.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    timing: (f = msg.getTiming()) && proto.onesie_request.timingData.toObject(includeInstance, f),
    request: (f = msg.getRequest()) && proto.onesie_request.request.toObject(includeInstance, f),
    ustreamerconfig: msg.getUstreamerconfig_asB64(),
    fiveint: jspb.Message.getFieldWithDefault(msg, 5, 0),
    screenheight: jspb.Message.getFieldWithDefault(msg, 6, 0),
    client: (f = msg.getClient()) && proto.onesie_request.clientMsg.toObject(includeInstance, f),
    thirteen: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.root}
 */
proto.onesie_request.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.root;
  return proto.onesie_request.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.root}
 */
proto.onesie_request.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.onesie_request.timingData;
      reader.readMessage(value,proto.onesie_request.timingData.deserializeBinaryFromReader);
      msg.setTiming(value);
      break;
    case 3:
      var value = new proto.onesie_request.request;
      reader.readMessage(value,proto.onesie_request.request.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setUstreamerconfig(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFiveint(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenheight(value);
      break;
    case 10:
      var value = new proto.onesie_request.clientMsg;
      reader.readMessage(value,proto.onesie_request.clientMsg.deserializeBinaryFromReader);
      msg.setClient(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setThirteen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTiming();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.onesie_request.timingData.serializeBinaryToWriter
    );
  }
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.onesie_request.request.serializeBinaryToWriter
    );
  }
  f = message.getUstreamerconfig_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getScreenheight();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getClient();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.onesie_request.clientMsg.serializeBinaryToWriter
    );
  }
  f = message.getThirteen();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
};


/**
 * optional timingData timing = 2;
 * @return {?proto.onesie_request.timingData}
 */
proto.onesie_request.root.prototype.getTiming = function() {
  return /** @type{?proto.onesie_request.timingData} */ (
    jspb.Message.getWrapperField(this, proto.onesie_request.timingData, 2));
};


/**
 * @param {?proto.onesie_request.timingData|undefined} value
 * @return {!proto.onesie_request.root} returns this
*/
proto.onesie_request.root.prototype.setTiming = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.clearTiming = function() {
  return this.setTiming(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.root.prototype.hasTiming = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional request request = 3;
 * @return {?proto.onesie_request.request}
 */
proto.onesie_request.root.prototype.getRequest = function() {
  return /** @type{?proto.onesie_request.request} */ (
    jspb.Message.getWrapperField(this, proto.onesie_request.request, 3));
};


/**
 * @param {?proto.onesie_request.request|undefined} value
 * @return {!proto.onesie_request.root} returns this
*/
proto.onesie_request.root.prototype.setRequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.root.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes ustreamerConfig = 4;
 * @return {!(string|Uint8Array)}
 */
proto.onesie_request.root.prototype.getUstreamerconfig = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes ustreamerConfig = 4;
 * This is a type-conversion wrapper around `getUstreamerconfig()`
 * @return {string}
 */
proto.onesie_request.root.prototype.getUstreamerconfig_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getUstreamerconfig()));
};


/**
 * optional bytes ustreamerConfig = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getUstreamerconfig()`
 * @return {!Uint8Array}
 */
proto.onesie_request.root.prototype.getUstreamerconfig_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getUstreamerconfig()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.setUstreamerconfig = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional int32 fiveint = 5;
 * @return {number}
 */
proto.onesie_request.root.prototype.getFiveint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.setFiveint = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.clearFiveint = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.root.prototype.hasFiveint = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 screenHeight = 6;
 * @return {number}
 */
proto.onesie_request.root.prototype.getScreenheight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.setScreenheight = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional clientMsg client = 10;
 * @return {?proto.onesie_request.clientMsg}
 */
proto.onesie_request.root.prototype.getClient = function() {
  return /** @type{?proto.onesie_request.clientMsg} */ (
    jspb.Message.getWrapperField(this, proto.onesie_request.clientMsg, 10));
};


/**
 * @param {?proto.onesie_request.clientMsg|undefined} value
 * @return {!proto.onesie_request.root} returns this
*/
proto.onesie_request.root.prototype.setClient = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.clearClient = function() {
  return this.setClient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.onesie_request.root.prototype.hasClient = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 thirteen = 13;
 * @return {number}
 */
proto.onesie_request.root.prototype.getThirteen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.onesie_request.root} returns this
 */
proto.onesie_request.root.prototype.setThirteen = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.onesie_request.part11Resp.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.onesie_request.part11Resp.prototype.toObject = function(opt_includeInstance) {
  return proto.onesie_request.part11Resp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.onesie_request.part11Resp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.part11Resp.toObject = function(includeInstance, msg) {
  var f, obj = {
    headerList: jspb.Message.toObjectList(msg.getHeaderList(),
    proto.onesie_request.requestHeader.toObject, includeInstance),
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.onesie_request.part11Resp}
 */
proto.onesie_request.part11Resp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.onesie_request.part11Resp;
  return proto.onesie_request.part11Resp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.onesie_request.part11Resp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.onesie_request.part11Resp}
 */
proto.onesie_request.part11Resp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = new proto.onesie_request.requestHeader;
      reader.readMessage(value,proto.onesie_request.requestHeader.deserializeBinaryFromReader);
      msg.addHeader(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.onesie_request.part11Resp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.onesie_request.part11Resp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.onesie_request.part11Resp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.onesie_request.part11Resp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaderList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.onesie_request.requestHeader.serializeBinaryToWriter
    );
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * repeated requestHeader header = 3;
 * @return {!Array<!proto.onesie_request.requestHeader>}
 */
proto.onesie_request.part11Resp.prototype.getHeaderList = function() {
  return /** @type{!Array<!proto.onesie_request.requestHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.onesie_request.requestHeader, 3));
};


/**
 * @param {!Array<!proto.onesie_request.requestHeader>} value
 * @return {!proto.onesie_request.part11Resp} returns this
*/
proto.onesie_request.part11Resp.prototype.setHeaderList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.onesie_request.requestHeader=} opt_value
 * @param {number=} opt_index
 * @return {!proto.onesie_request.requestHeader}
 */
proto.onesie_request.part11Resp.prototype.addHeader = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.onesie_request.requestHeader, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.onesie_request.part11Resp} returns this
 */
proto.onesie_request.part11Resp.prototype.clearHeaderList = function() {
  return this.setHeaderList([]);
};


/**
 * optional bytes body = 4;
 * @return {!(string|Uint8Array)}
 */
proto.onesie_request.part11Resp.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes body = 4;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.onesie_request.part11Resp.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.onesie_request.part11Resp.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.onesie_request.part11Resp} returns this
 */
proto.onesie_request.part11Resp.prototype.setBody = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


goog.object.extend(exports, proto.onesie_request);
