// source: popularVidsChip.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.popularVidsChip.vidsChip', null, global);
goog.exportSymbol('proto.popularVidsChip.vidsChip.nestedMsg1', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.popularVidsChip.vidsChip = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.popularVidsChip.vidsChip.repeatedFields_, null);
};
goog.inherits(proto.popularVidsChip.vidsChip, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.popularVidsChip.vidsChip.displayName = 'proto.popularVidsChip.vidsChip';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.popularVidsChip.vidsChip.nestedMsg1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.popularVidsChip.vidsChip.nestedMsg1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.popularVidsChip.vidsChip.nestedMsg1.displayName = 'proto.popularVidsChip.vidsChip.nestedMsg1';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.popularVidsChip.vidsChip.repeatedFields_ = [80226972];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.popularVidsChip.vidsChip.prototype.toObject = function(opt_includeInstance) {
  return proto.popularVidsChip.vidsChip.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.popularVidsChip.vidsChip} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.popularVidsChip.vidsChip.toObject = function(includeInstance, msg) {
  var f, obj = {
    dummy: jspb.Message.getFieldWithDefault(msg, 1, ""),
    msgList: jspb.Message.toObjectList(msg.getMsgList(),
    proto.popularVidsChip.vidsChip.nestedMsg1.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.popularVidsChip.vidsChip}
 */
proto.popularVidsChip.vidsChip.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.popularVidsChip.vidsChip;
  return proto.popularVidsChip.vidsChip.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.popularVidsChip.vidsChip} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.popularVidsChip.vidsChip}
 */
proto.popularVidsChip.vidsChip.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDummy(value);
      break;
    case 80226972:
      var value = new proto.popularVidsChip.vidsChip.nestedMsg1;
      reader.readMessage(value,proto.popularVidsChip.vidsChip.nestedMsg1.deserializeBinaryFromReader);
      msg.addMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.popularVidsChip.vidsChip.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.popularVidsChip.vidsChip.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.popularVidsChip.vidsChip} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.popularVidsChip.vidsChip.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDummy();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMsgList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      80226972,
      f,
      proto.popularVidsChip.vidsChip.nestedMsg1.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.toObject = function(opt_includeInstance) {
  return proto.popularVidsChip.vidsChip.nestedMsg1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.popularVidsChip.vidsChip.nestedMsg1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.popularVidsChip.vidsChip.nestedMsg1.toObject = function(includeInstance, msg) {
  var f, obj = {
    channelid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    chipparam: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.popularVidsChip.vidsChip.nestedMsg1}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.popularVidsChip.vidsChip.nestedMsg1;
  return proto.popularVidsChip.vidsChip.nestedMsg1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.popularVidsChip.vidsChip.nestedMsg1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.popularVidsChip.vidsChip.nestedMsg1}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setChipparam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.popularVidsChip.vidsChip.nestedMsg1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.popularVidsChip.vidsChip.nestedMsg1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.popularVidsChip.vidsChip.nestedMsg1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChipparam();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string channelId = 2;
 * @return {string}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.popularVidsChip.vidsChip.nestedMsg1} returns this
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string chipParam = 3;
 * @return {string}
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.getChipparam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.popularVidsChip.vidsChip.nestedMsg1} returns this
 */
proto.popularVidsChip.vidsChip.nestedMsg1.prototype.setChipparam = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string dummy = 1;
 * @return {string}
 */
proto.popularVidsChip.vidsChip.prototype.getDummy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.popularVidsChip.vidsChip} returns this
 */
proto.popularVidsChip.vidsChip.prototype.setDummy = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated nestedMsg1 msg = 80226972;
 * @return {!Array<!proto.popularVidsChip.vidsChip.nestedMsg1>}
 */
proto.popularVidsChip.vidsChip.prototype.getMsgList = function() {
  return /** @type{!Array<!proto.popularVidsChip.vidsChip.nestedMsg1>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.popularVidsChip.vidsChip.nestedMsg1, 80226972));
};


/**
 * @param {!Array<!proto.popularVidsChip.vidsChip.nestedMsg1>} value
 * @return {!proto.popularVidsChip.vidsChip} returns this
*/
proto.popularVidsChip.vidsChip.prototype.setMsgList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 80226972, value);
};


/**
 * @param {!proto.popularVidsChip.vidsChip.nestedMsg1=} opt_value
 * @param {number=} opt_index
 * @return {!proto.popularVidsChip.vidsChip.nestedMsg1}
 */
proto.popularVidsChip.vidsChip.prototype.addMsg = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 80226972, opt_value, proto.popularVidsChip.vidsChip.nestedMsg1, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.popularVidsChip.vidsChip} returns this
 */
proto.popularVidsChip.vidsChip.prototype.clearMsgList = function() {
  return this.setMsgList([]);
};


goog.object.extend(exports, proto.popularVidsChip);
