// source: temp_behalfof.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.temp_behalfof.behalf', null, global);
goog.exportSymbol('proto.temp_behalfof.root', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temp_behalfof.behalf = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.temp_behalfof.behalf, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.temp_behalfof.behalf.displayName = 'proto.temp_behalfof.behalf';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.temp_behalfof.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.temp_behalfof.root.repeatedFields_, null);
};
goog.inherits(proto.temp_behalfof.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.temp_behalfof.root.displayName = 'proto.temp_behalfof.root';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temp_behalfof.behalf.prototype.toObject = function(opt_includeInstance) {
  return proto.temp_behalfof.behalf.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temp_behalfof.behalf} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temp_behalfof.behalf.toObject = function(includeInstance, msg) {
  var f, obj = {
    channelid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    empty2: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temp_behalfof.behalf}
 */
proto.temp_behalfof.behalf.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temp_behalfof.behalf;
  return proto.temp_behalfof.behalf.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temp_behalfof.behalf} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temp_behalfof.behalf}
 */
proto.temp_behalfof.behalf.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmpty2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temp_behalfof.behalf.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temp_behalfof.behalf.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temp_behalfof.behalf} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temp_behalfof.behalf.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmpty2();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string channelId = 1;
 * @return {string}
 */
proto.temp_behalfof.behalf.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.temp_behalfof.behalf} returns this
 */
proto.temp_behalfof.behalf.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string empty2 = 2;
 * @return {string}
 */
proto.temp_behalfof.behalf.prototype.getEmpty2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.temp_behalfof.behalf} returns this
 */
proto.temp_behalfof.behalf.prototype.setEmpty2 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.temp_behalfof.root.repeatedFields_ = [170];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.temp_behalfof.root.prototype.toObject = function(opt_includeInstance) {
  return proto.temp_behalfof.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.temp_behalfof.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temp_behalfof.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    behList: jspb.Message.toObjectList(msg.getBehList(),
    proto.temp_behalfof.behalf.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.temp_behalfof.root}
 */
proto.temp_behalfof.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.temp_behalfof.root;
  return proto.temp_behalfof.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.temp_behalfof.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.temp_behalfof.root}
 */
proto.temp_behalfof.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 170:
      var value = new proto.temp_behalfof.behalf;
      reader.readMessage(value,proto.temp_behalfof.behalf.deserializeBinaryFromReader);
      msg.addBeh(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.temp_behalfof.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.temp_behalfof.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.temp_behalfof.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.temp_behalfof.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBehList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      170,
      f,
      proto.temp_behalfof.behalf.serializeBinaryToWriter
    );
  }
};


/**
 * repeated behalf beh = 170;
 * @return {!Array<!proto.temp_behalfof.behalf>}
 */
proto.temp_behalfof.root.prototype.getBehList = function() {
  return /** @type{!Array<!proto.temp_behalfof.behalf>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.temp_behalfof.behalf, 170));
};


/**
 * @param {!Array<!proto.temp_behalfof.behalf>} value
 * @return {!proto.temp_behalfof.root} returns this
*/
proto.temp_behalfof.root.prototype.setBehList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 170, value);
};


/**
 * @param {!proto.temp_behalfof.behalf=} opt_value
 * @param {number=} opt_index
 * @return {!proto.temp_behalfof.behalf}
 */
proto.temp_behalfof.root.prototype.addBeh = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 170, opt_value, proto.temp_behalfof.behalf, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.temp_behalfof.root} returns this
 */
proto.temp_behalfof.root.prototype.clearBehList = function() {
  return this.setBehList([]);
};


goog.object.extend(exports, proto.temp_behalfof);
