// source: watchNextFeed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.watchNextRelatedFeed.root', null, global);
goog.exportSymbol('proto.watchNextRelatedFeed.root.container', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.watchNextRelatedFeed.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.watchNextRelatedFeed.root.repeatedFields_, null);
};
goog.inherits(proto.watchNextRelatedFeed.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.watchNextRelatedFeed.root.displayName = 'proto.watchNextRelatedFeed.root';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.watchNextRelatedFeed.root.container = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.watchNextRelatedFeed.root.container, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.watchNextRelatedFeed.root.container.displayName = 'proto.watchNextRelatedFeed.root.container';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.watchNextRelatedFeed.root.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.watchNextRelatedFeed.root.prototype.toObject = function(opt_includeInstance) {
  return proto.watchNextRelatedFeed.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.watchNextRelatedFeed.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.watchNextRelatedFeed.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    constant40: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cList: jspb.Message.toObjectList(msg.getCList(),
    proto.watchNextRelatedFeed.root.container.toObject, includeInstance),
    zeroint: jspb.Message.getFieldWithDefault(msg, 3, 0),
    continuation: jspb.Message.getFieldWithDefault(msg, 5, ""),
    watchnextfeed: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.watchNextRelatedFeed.root}
 */
proto.watchNextRelatedFeed.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.watchNextRelatedFeed.root;
  return proto.watchNextRelatedFeed.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.watchNextRelatedFeed.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.watchNextRelatedFeed.root}
 */
proto.watchNextRelatedFeed.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setConstant40(value);
      break;
    case 2:
      var value = new proto.watchNextRelatedFeed.root.container;
      reader.readMessage(value,proto.watchNextRelatedFeed.root.container.deserializeBinaryFromReader);
      msg.addC(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setZeroint(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContinuation(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setWatchnextfeed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.watchNextRelatedFeed.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.watchNextRelatedFeed.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.watchNextRelatedFeed.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.watchNextRelatedFeed.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConstant40();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.watchNextRelatedFeed.root.container.serializeBinaryToWriter
    );
  }
  f = message.getZeroint();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getContinuation();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getWatchnextfeed();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.watchNextRelatedFeed.root.container.prototype.toObject = function(opt_includeInstance) {
  return proto.watchNextRelatedFeed.root.container.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.watchNextRelatedFeed.root.container} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.watchNextRelatedFeed.root.container.toObject = function(includeInstance, msg) {
  var f, obj = {
    video: jspb.Message.getFieldWithDefault(msg, 2, ""),
    zeroint: jspb.Message.getFieldWithDefault(msg, 25, 0),
    threeint: jspb.Message.getFieldWithDefault(msg, 28, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.watchNextRelatedFeed.root.container}
 */
proto.watchNextRelatedFeed.root.container.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.watchNextRelatedFeed.root.container;
  return proto.watchNextRelatedFeed.root.container.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.watchNextRelatedFeed.root.container} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.watchNextRelatedFeed.root.container}
 */
proto.watchNextRelatedFeed.root.container.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVideo(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setZeroint(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setThreeint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.watchNextRelatedFeed.root.container.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.watchNextRelatedFeed.root.container.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.watchNextRelatedFeed.root.container} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.watchNextRelatedFeed.root.container.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVideo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getZeroint();
  if (f !== 0) {
    writer.writeInt64(
      25,
      f
    );
  }
  f = message.getThreeint();
  if (f !== 0) {
    writer.writeInt64(
      28,
      f
    );
  }
};


/**
 * optional string video = 2;
 * @return {string}
 */
proto.watchNextRelatedFeed.root.container.prototype.getVideo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.watchNextRelatedFeed.root.container} returns this
 */
proto.watchNextRelatedFeed.root.container.prototype.setVideo = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 zeroInt = 25;
 * @return {number}
 */
proto.watchNextRelatedFeed.root.container.prototype.getZeroint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/**
 * @param {number} value
 * @return {!proto.watchNextRelatedFeed.root.container} returns this
 */
proto.watchNextRelatedFeed.root.container.prototype.setZeroint = function(value) {
  return jspb.Message.setProto3IntField(this, 25, value);
};


/**
 * optional int64 threeInt = 28;
 * @return {number}
 */
proto.watchNextRelatedFeed.root.container.prototype.getThreeint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.watchNextRelatedFeed.root.container} returns this
 */
proto.watchNextRelatedFeed.root.container.prototype.setThreeint = function(value) {
  return jspb.Message.setProto3IntField(this, 28, value);
};


/**
 * optional int64 constant40 = 1;
 * @return {number}
 */
proto.watchNextRelatedFeed.root.prototype.getConstant40 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.watchNextRelatedFeed.root} returns this
 */
proto.watchNextRelatedFeed.root.prototype.setConstant40 = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated container c = 2;
 * @return {!Array<!proto.watchNextRelatedFeed.root.container>}
 */
proto.watchNextRelatedFeed.root.prototype.getCList = function() {
  return /** @type{!Array<!proto.watchNextRelatedFeed.root.container>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.watchNextRelatedFeed.root.container, 2));
};


/**
 * @param {!Array<!proto.watchNextRelatedFeed.root.container>} value
 * @return {!proto.watchNextRelatedFeed.root} returns this
*/
proto.watchNextRelatedFeed.root.prototype.setCList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.watchNextRelatedFeed.root.container=} opt_value
 * @param {number=} opt_index
 * @return {!proto.watchNextRelatedFeed.root.container}
 */
proto.watchNextRelatedFeed.root.prototype.addC = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.watchNextRelatedFeed.root.container, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.watchNextRelatedFeed.root} returns this
 */
proto.watchNextRelatedFeed.root.prototype.clearCList = function() {
  return this.setCList([]);
};


/**
 * optional int64 zeroInt = 3;
 * @return {number}
 */
proto.watchNextRelatedFeed.root.prototype.getZeroint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.watchNextRelatedFeed.root} returns this
 */
proto.watchNextRelatedFeed.root.prototype.setZeroint = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string continuation = 5;
 * @return {string}
 */
proto.watchNextRelatedFeed.root.prototype.getContinuation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.watchNextRelatedFeed.root} returns this
 */
proto.watchNextRelatedFeed.root.prototype.setContinuation = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string watchNextFeed = 13;
 * @return {string}
 */
proto.watchNextRelatedFeed.root.prototype.getWatchnextfeed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.watchNextRelatedFeed.root} returns this
 */
proto.watchNextRelatedFeed.root.prototype.setWatchnextfeed = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


goog.object.extend(exports, proto.watchNextRelatedFeed);
