// source: yt2009_channel.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yt2009_channel_customizations.featuredChannel', null, global);
goog.exportSymbol('proto.yt2009_channel_customizations.root', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yt2009_channel_customizations.featuredChannel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yt2009_channel_customizations.featuredChannel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yt2009_channel_customizations.featuredChannel.displayName = 'proto.yt2009_channel_customizations.featuredChannel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yt2009_channel_customizations.root = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yt2009_channel_customizations.root.repeatedFields_, null);
};
goog.inherits(proto.yt2009_channel_customizations.root, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yt2009_channel_customizations.root.displayName = 'proto.yt2009_channel_customizations.root';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.toObject = function(opt_includeInstance) {
  return proto.yt2009_channel_customizations.featuredChannel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yt2009_channel_customizations.featuredChannel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yt2009_channel_customizations.featuredChannel.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pictureurl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yt2009_channel_customizations.featuredChannel}
 */
proto.yt2009_channel_customizations.featuredChannel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yt2009_channel_customizations.featuredChannel;
  return proto.yt2009_channel_customizations.featuredChannel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yt2009_channel_customizations.featuredChannel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yt2009_channel_customizations.featuredChannel}
 */
proto.yt2009_channel_customizations.featuredChannel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPictureurl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yt2009_channel_customizations.featuredChannel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yt2009_channel_customizations.featuredChannel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yt2009_channel_customizations.featuredChannel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPictureurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.featuredChannel} returns this
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.featuredChannel} returns this
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string pictureUrl = 3;
 * @return {string}
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.getPictureurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.featuredChannel} returns this
 */
proto.yt2009_channel_customizations.featuredChannel.prototype.setPictureurl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yt2009_channel_customizations.root.repeatedFields_ = [19,20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yt2009_channel_customizations.root.prototype.toObject = function(opt_includeInstance) {
  return proto.yt2009_channel_customizations.root.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yt2009_channel_customizations.root} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yt2009_channel_customizations.root.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tags: jspb.Message.getFieldWithDefault(msg, 3, ""),
    themeid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    font: jspb.Message.getFieldWithDefault(msg, 5, 0),
    backgroundcolor: jspb.Message.getFieldWithDefault(msg, 6, ""),
    wrappercolor: jspb.Message.getFieldWithDefault(msg, 7, ""),
    wrappertextcolor: jspb.Message.getFieldWithDefault(msg, 8, ""),
    wrapperlinkcolor: jspb.Message.getFieldWithDefault(msg, 9, ""),
    wrapperopacity: jspb.Message.getFieldWithDefault(msg, 10, 0),
    custombackgroundid: jspb.Message.getFieldWithDefault(msg, 11, ""),
    repeatcustombackground: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    innerboxbackgroundcolor: jspb.Message.getFieldWithDefault(msg, 13, ""),
    innerboxtitletextcolor: jspb.Message.getFieldWithDefault(msg, 14, ""),
    innerboxlinkcolor: jspb.Message.getFieldWithDefault(msg, 15, ""),
    innerboxbodytextcolor: jspb.Message.getFieldWithDefault(msg, 16, ""),
    innerboxopacity: jspb.Message.getFieldWithDefault(msg, 17, 0),
    shownmodules: jspb.Message.getFieldWithDefault(msg, 18, ""),
    subscriberList: jspb.Message.toObjectList(msg.getSubscriberList(),
    proto.yt2009_channel_customizations.featuredChannel.toObject, includeInstance),
    subscriptionList: jspb.Message.toObjectList(msg.getSubscriptionList(),
    proto.yt2009_channel_customizations.featuredChannel.toObject, includeInstance),
    showncontent: jspb.Message.getFieldWithDefault(msg, 21, ""),
    defaultgrid: jspb.Message.getBooleanFieldWithDefault(msg, 22, false),
    altdefaultset: jspb.Message.getFieldWithDefault(msg, 23, 0),
    altdefaultvidid: jspb.Message.getFieldWithDefault(msg, 24, ""),
    hidebanner: jspb.Message.getBooleanFieldWithDefault(msg, 25, false),
    enableautoplay: jspb.Message.getBooleanFieldWithDefault(msg, 26, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yt2009_channel_customizations.root}
 */
proto.yt2009_channel_customizations.root.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yt2009_channel_customizations.root;
  return proto.yt2009_channel_customizations.root.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yt2009_channel_customizations.root} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yt2009_channel_customizations.root}
 */
proto.yt2009_channel_customizations.root.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setThemeid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFont(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBackgroundcolor(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setWrappercolor(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWrappertextcolor(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setWrapperlinkcolor(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWrapperopacity(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustombackgroundid(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRepeatcustombackground(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setInnerboxbackgroundcolor(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setInnerboxtitletextcolor(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setInnerboxlinkcolor(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setInnerboxbodytextcolor(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInnerboxopacity(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setShownmodules(value);
      break;
    case 19:
      var value = new proto.yt2009_channel_customizations.featuredChannel;
      reader.readMessage(value,proto.yt2009_channel_customizations.featuredChannel.deserializeBinaryFromReader);
      msg.addSubscriber(value);
      break;
    case 20:
      var value = new proto.yt2009_channel_customizations.featuredChannel;
      reader.readMessage(value,proto.yt2009_channel_customizations.featuredChannel.deserializeBinaryFromReader);
      msg.addSubscription(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setShowncontent(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDefaultgrid(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAltdefaultset(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setAltdefaultvidid(value);
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHidebanner(value);
      break;
    case 26:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableautoplay(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yt2009_channel_customizations.root.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yt2009_channel_customizations.root.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yt2009_channel_customizations.root} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yt2009_channel_customizations.root.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getBackgroundcolor();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getWrappercolor();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWrappertextcolor();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getWrapperlinkcolor();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getCustombackgroundid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getRepeatcustombackground();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getInnerboxbackgroundcolor();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getInnerboxtitletextcolor();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getInnerboxlinkcolor();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getInnerboxbodytextcolor();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = message.getShownmodules();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getSubscriberList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto.yt2009_channel_customizations.featuredChannel.serializeBinaryToWriter
    );
  }
  f = message.getSubscriptionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.yt2009_channel_customizations.featuredChannel.serializeBinaryToWriter
    );
  }
  f = message.getShowncontent();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getDefaultgrid();
  if (f) {
    writer.writeBool(
      22,
      f
    );
  }
  f = message.getAltdefaultset();
  if (f !== 0) {
    writer.writeInt32(
      23,
      f
    );
  }
  f = message.getAltdefaultvidid();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getHidebanner();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getEnableautoplay();
  if (f) {
    writer.writeBool(
      26,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tags = 3;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setTags = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 themeId = 4;
 * @return {number}
 */
proto.yt2009_channel_customizations.root.prototype.getThemeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setThemeid = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearThemeid = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.hasThemeid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 font = 5;
 * @return {number}
 */
proto.yt2009_channel_customizations.root.prototype.getFont = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setFont = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearFont = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.hasFont = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string backgroundColor = 6;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getBackgroundcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setBackgroundcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string wrapperColor = 7;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getWrappercolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setWrappercolor = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string wrapperTextColor = 8;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getWrappertextcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setWrappertextcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string wrapperLinkColor = 9;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getWrapperlinkcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setWrapperlinkcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 wrapperOpacity = 10;
 * @return {number}
 */
proto.yt2009_channel_customizations.root.prototype.getWrapperopacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setWrapperopacity = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearWrapperopacity = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.hasWrapperopacity = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string customBackgroundId = 11;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getCustombackgroundid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setCustombackgroundid = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool repeatCustomBackground = 12;
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.getRepeatcustombackground = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setRepeatcustombackground = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string innerboxBackgroundColor = 13;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getInnerboxbackgroundcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setInnerboxbackgroundcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string innerboxTitleTextColor = 14;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getInnerboxtitletextcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setInnerboxtitletextcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string innerboxLinkColor = 15;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getInnerboxlinkcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setInnerboxlinkcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string innerboxBodyTextColor = 16;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getInnerboxbodytextcolor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setInnerboxbodytextcolor = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional int32 innerboxOpacity = 17;
 * @return {number}
 */
proto.yt2009_channel_customizations.root.prototype.getInnerboxopacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setInnerboxopacity = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearInnerboxopacity = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.hasInnerboxopacity = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional string shownModules = 18;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getShownmodules = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setShownmodules = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * repeated featuredChannel subscriber = 19;
 * @return {!Array<!proto.yt2009_channel_customizations.featuredChannel>}
 */
proto.yt2009_channel_customizations.root.prototype.getSubscriberList = function() {
  return /** @type{!Array<!proto.yt2009_channel_customizations.featuredChannel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yt2009_channel_customizations.featuredChannel, 19));
};


/**
 * @param {!Array<!proto.yt2009_channel_customizations.featuredChannel>} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
*/
proto.yt2009_channel_customizations.root.prototype.setSubscriberList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.yt2009_channel_customizations.featuredChannel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yt2009_channel_customizations.featuredChannel}
 */
proto.yt2009_channel_customizations.root.prototype.addSubscriber = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.yt2009_channel_customizations.featuredChannel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearSubscriberList = function() {
  return this.setSubscriberList([]);
};


/**
 * repeated featuredChannel subscription = 20;
 * @return {!Array<!proto.yt2009_channel_customizations.featuredChannel>}
 */
proto.yt2009_channel_customizations.root.prototype.getSubscriptionList = function() {
  return /** @type{!Array<!proto.yt2009_channel_customizations.featuredChannel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yt2009_channel_customizations.featuredChannel, 20));
};


/**
 * @param {!Array<!proto.yt2009_channel_customizations.featuredChannel>} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
*/
proto.yt2009_channel_customizations.root.prototype.setSubscriptionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.yt2009_channel_customizations.featuredChannel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yt2009_channel_customizations.featuredChannel}
 */
proto.yt2009_channel_customizations.root.prototype.addSubscription = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.yt2009_channel_customizations.featuredChannel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.clearSubscriptionList = function() {
  return this.setSubscriptionList([]);
};


/**
 * optional string shownContent = 21;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getShowncontent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setShowncontent = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional bool defaultGrid = 22;
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.getDefaultgrid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 22, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setDefaultgrid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 22, value);
};


/**
 * optional int32 altDefaultSet = 23;
 * @return {number}
 */
proto.yt2009_channel_customizations.root.prototype.getAltdefaultset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setAltdefaultset = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * optional string altDefaultVidId = 24;
 * @return {string}
 */
proto.yt2009_channel_customizations.root.prototype.getAltdefaultvidid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setAltdefaultvidid = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional bool hideBanner = 25;
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.getHidebanner = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 25, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setHidebanner = function(value) {
  return jspb.Message.setProto3BooleanField(this, 25, value);
};


/**
 * optional bool enableAutoplay = 26;
 * @return {boolean}
 */
proto.yt2009_channel_customizations.root.prototype.getEnableautoplay = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 26, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yt2009_channel_customizations.root} returns this
 */
proto.yt2009_channel_customizations.root.prototype.setEnableautoplay = function(value) {
  return jspb.Message.setProto3BooleanField(this, 26, value);
};


goog.object.extend(exports, proto.yt2009_channel_customizations);
